# Generated by Django 5.1.15 on 2026-02-06 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plugin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("version", models.CharField(max_length=20)),
                ("provider", models.CharField(max_length=100)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="InstalledPlugin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_id", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("installed", "Installed"),
                            ("active", "Active"),
                            ("disabled", "Disabled"),
                            ("uninstalled", "Uninstalled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="plugins.plugin"
                    ),
                ),
            ],
            options={
                "unique_together": {("plugin", "store_id")},
            },
        ),
    ]
