"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from urllib.parse import urlparse
from pathlib import Path
import importlib.util
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

def _env_bool(name: str, default: str = "0") -> bool:
    return os.getenv(name, default).strip().lower() in ("1", "true", "yes", "on")


def _env_list(name: str, default: list[str] | None = None) -> list[str]:
    raw = os.getenv(name, "")
    if raw.strip():
        return [item.strip() for item in raw.split(",") if item.strip()]
    return list(default or [])


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
ENVIRONMENT = os.getenv("ENVIRONMENT", "development").strip().lower() or "development"

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "").strip()
if not SECRET_KEY:
    if ENVIRONMENT == "production":
        raise ImproperlyConfigured("DJANGO_SECRET_KEY is required in production")
    SECRET_KEY = "dev-insecure-change-me"

DEBUG = _env_bool("DJANGO_DEBUG", "0" if ENVIRONMENT == "production" else "1")
TEST_OTP_CODE = os.getenv("TEST_OTP_CODE", "123456").strip() or "123456"
SECURITY_CSP_ENABLED = _env_bool("SECURITY_CSP_ENABLED", "1")
ADMIN_PORTAL_2FA_ENABLED = _env_bool("ADMIN_PORTAL_2FA_ENABLED", "1" if ENVIRONMENT == "production" else "0")
ADMIN_PORTAL_2FA_TTL_SECONDS = int(os.getenv("ADMIN_PORTAL_2FA_TTL_SECONDS", "300") or "300")

SECURITY_RATE_LIMITS = [
    {
        "key": "login_user",
        "pattern": r"^/auth/$",
        "methods": ["POST"],
        "limit": int(os.getenv("RL_LOGIN_LIMIT", "10") or "10"),
        "window": int(os.getenv("RL_LOGIN_WINDOW", "300") or "300"),
        "message_key": "login_rate_limited",
    },
    {
        "key": "login_admin",
        "pattern": r"^/admin-portal/login/$",
        "methods": ["POST"],
        "limit": int(os.getenv("RL_ADMIN_LOGIN_LIMIT", "8") or "8"),
        "window": int(os.getenv("RL_ADMIN_LOGIN_WINDOW", "300") or "300"),
        "message_key": "admin_login_rate_limited",
    },
    {
        "key": "otp_verify",
        "pattern": r"^/auth/(verify|resend)/$",
        "methods": ["POST"],
        "limit": int(os.getenv("RL_OTP_LIMIT", "10") or "10"),
        "window": int(os.getenv("RL_OTP_WINDOW", "300") or "300"),
        "message_key": "otp_rate_limited",
    },
    {
        "key": "payments",
        "pattern": r"^/api/payments/",
        "methods": ["POST", "PUT", "PATCH", "DELETE"],
        "limit": int(os.getenv("RL_PAYMENTS_LIMIT", "60") or "60"),
        "window": int(os.getenv("RL_PAYMENTS_WINDOW", "60") or "60"),
        "message_key": "payments_rate_limited",
    },
]

WASSLA_BASE_DOMAIN = os.getenv("WASSLA_BASE_DOMAIN", "w-sala.com").strip().lower() or "w-sala.com"

ALLOWED_HOSTS = _env_list(
    "DJANGO_ALLOWED_HOSTS",
    default=[
        "localhost",
        "127.0.0.1",
        "[::1]",
        WASSLA_BASE_DOMAIN,
        f".{WASSLA_BASE_DOMAIN}",
        f"www.{WASSLA_BASE_DOMAIN}",
        "76.13.143.149",
        "store1.127.0.0.1.nip.io",
        ".nip.io",
        ".127.0.0.1.nip.io",
        "w-sala.com",
    ],
)

CSRF_TRUSTED_ORIGINS = _env_list(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    default=[
        "http://127.0.0.1:8000",
        "http://localhost:8000",
        "http://*.nip.io",
        "http://*.127.0.0.1.nip.io:8000",
        "http://*.nip.io:8000",
        "https://w-sala.com",
        "https://*.w-sala.com",
    ],
)

# Custom domains (multi-tenant mapping)
CUSTOM_DOMAIN_SERVER_IP = os.getenv("CUSTOM_DOMAIN_SERVER_IP", "").strip()
CUSTOM_DOMAIN_CNAME_TARGET = os.getenv("CUSTOM_DOMAIN_CNAME_TARGET", "").strip()
CUSTOM_DOMAIN_BLOCKED_DOMAINS = _env_list("CUSTOM_DOMAIN_BLOCKED_DOMAINS", default=[WASSLA_BASE_DOMAIN])
CUSTOM_DOMAIN_VERIFICATION_PATH_PREFIX = os.getenv(
    "CUSTOM_DOMAIN_VERIFICATION_PATH_PREFIX",
    "/.well-known/wassla-domain-verification",
).strip()
CUSTOM_DOMAIN_HTTP_TIMEOUT_SECONDS = int(os.getenv("CUSTOM_DOMAIN_HTTP_TIMEOUT_SECONDS", "5") or "5")
CUSTOM_DOMAIN_VERIFY_MIN_INTERVAL_SECONDS = int(
    os.getenv("CUSTOM_DOMAIN_VERIFY_MIN_INTERVAL_SECONDS", "30") or "30"
)
CUSTOM_DOMAIN_DNS_CACHE_SECONDS = int(os.getenv("CUSTOM_DOMAIN_DNS_CACHE_SECONDS", "300") or "300")
CUSTOM_DOMAIN_CACHE_SECONDS = int(os.getenv("CUSTOM_DOMAIN_CACHE_SECONDS", "300") or "300")

# SSL/Certbot
CUSTOM_DOMAIN_SSL_ENABLED = _env_bool("CUSTOM_DOMAIN_SSL_ENABLED", "0")
CUSTOM_DOMAIN_CERTBOT_CMD = os.getenv("CUSTOM_DOMAIN_CERTBOT_CMD", "certbot").strip() or "certbot"
CUSTOM_DOMAIN_CERTBOT_EMAIL = os.getenv("CUSTOM_DOMAIN_CERTBOT_EMAIL", "").strip()
CUSTOM_DOMAIN_CERTBOT_MODE = os.getenv("CUSTOM_DOMAIN_CERTBOT_MODE", "http-01").strip() or "http-01"
CUSTOM_DOMAIN_CERTBOT_WEBROOT = os.getenv(
    "CUSTOM_DOMAIN_CERTBOT_WEBROOT",
    "/var/www/certbot",
).strip()
CUSTOM_DOMAIN_CERTBOT_DNS_AUTH_HOOK = os.getenv("CUSTOM_DOMAIN_CERTBOT_DNS_AUTH_HOOK", "").strip()
CUSTOM_DOMAIN_CERTBOT_DNS_CLEANUP_HOOK = os.getenv("CUSTOM_DOMAIN_CERTBOT_DNS_CLEANUP_HOOK", "").strip()
CUSTOM_DOMAIN_CERTS_DIR = os.getenv("CUSTOM_DOMAIN_CERTS_DIR", "/etc/letsencrypt/live").strip()

# Nginx dynamic config
CUSTOM_DOMAIN_NGINX_ENABLED = _env_bool("CUSTOM_DOMAIN_NGINX_ENABLED", "0")
CUSTOM_DOMAIN_NGINX_DOMAINS_DIR = os.getenv(
    "CUSTOM_DOMAIN_NGINX_DOMAINS_DIR",
    "/etc/nginx/conf.d/wasla_domains",
).strip()
CUSTOM_DOMAIN_NGINX_UPSTREAM = os.getenv(
    "CUSTOM_DOMAIN_NGINX_UPSTREAM",
    "http://127.0.0.1:8000",
).strip()
CUSTOM_DOMAIN_NGINX_TEST_CMD = os.getenv("CUSTOM_DOMAIN_NGINX_TEST_CMD", "nginx -t").strip()
CUSTOM_DOMAIN_NGINX_RELOAD_CMD = os.getenv("CUSTOM_DOMAIN_NGINX_RELOAD_CMD", "systemctl reload nginx").strip()
CUSTOM_DOMAIN_FORCE_HTTPS = _env_bool("CUSTOM_DOMAIN_FORCE_HTTPS", "0")
CUSTOM_DOMAIN_NGINX_RELOAD_IN_REQUEST = _env_bool("CUSTOM_DOMAIN_NGINX_RELOAD_IN_REQUEST", "0")
DOMAIN_PROVISIONING_MODE = os.getenv("DOMAIN_PROVISIONING_MODE", "manual").strip().lower() or "manual"
WASLA_ENABLE_AR = _env_bool("WASLA_ENABLE_AR", "0")

NGINX_TEMPLATE_DIR = os.getenv("NGINX_TEMPLATE_DIR", "infrastructure/nginx").strip() or "infrastructure/nginx"
NGINX_DOMAIN_TEMPLATE = os.getenv("NGINX_DOMAIN_TEMPLATE", "domain.conf.j2").strip() or "domain.conf.j2"



# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "rest_framework_simplejwt.token_blacklist",
    "apps.accounts.apps.AccountsConfig",
    "apps.sms.apps.SmsConfig",
    "apps.notifications.apps.NotificationsConfig",
    "apps.tenants.apps.TenantsConfig",
    "apps.catalog.apps.CatalogConfig",
    "apps.customers.apps.CustomerConfig",
    "apps.cart.apps.CartConfig",
    "apps.checkout.apps.CheckoutConfig",
    "apps.orders.apps.OrderConfig",
    "apps.purchases.apps.PurchasesConfig",
    "apps.payments.apps.PaymentConfig",
    "apps.imports.apps.ImportsConfig",
    "apps.themes.apps.ThemesConfig",
    "apps.exports.apps.ExportsConfig",
    "apps.settlements.apps.SettlementsConfig",
    "apps.ai.apps.AiConfig",
    "apps.ai_onboarding.apps.AiOnboardingConfig",
    "apps.domains.apps.DomainsConfig",
    "apps.observability.apps.ObservabilityConfig",
    "apps.security.apps.SecurityConfig",
    "apps.analytics.apps.AnalyticsConfig",
    "apps.plugins.apps.PluginsConfig",
    "apps.reviews.apps.ReviewsConfig",
    "apps.shipping.apps.ShippingConfig",
    "apps.subscriptions.apps.SubscriptionConfig",
    "apps.wallet.apps.WalletConfig",
    "apps.emails.apps.EmailsConfig",
    "apps.webhooks.apps.WebhooksConfig",
    "apps.system.apps.SystemConfig",
    "apps.stores.apps.StoresConfig",
    "apps.visual_search.apps.VisualSearchConfig",
    "apps.admin_portal.apps.AdminPortalConfig",
]

if importlib.util.find_spec("django_celery_beat"):
    INSTALLED_APPS.append("django_celery_beat")

if WASLA_ENABLE_AR:
    INSTALLED_APPS.append("apps.ar.apps.ArConfig")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "apps.security.middleware.rate_limit.RateLimitMiddleware",
    "apps.system.middleware.FriendlyErrorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "apps.tenants.middleware.TenantResolverMiddleware",
    "apps.security.middleware.headers.SecurityHeadersMiddleware",
    "apps.observability.middleware.request_id.RequestIdMiddleware",
    "apps.admin_portal.middleware.AdminPortalSecurityHeadersMiddleware",
    "apps.tenants.middleware.TenantLocaleMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "apps.observability.middleware.timing.PerformanceMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "apps.security.middleware.audit.SecurityAuditMiddleware",
    "apps.security.middleware.rbac.PermissionCacheMiddleware",
    "apps.accounts.middleware.OnboardingFlowMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.tenants.context_processors.merchant_status_context",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DB_DEFAULT_ALIAS = (os.getenv("DJANGO_DB_DEFAULT", "sqlite") or "sqlite").strip().lower()

# Local/dev safety: if someone sets mysql but mysqlclient isn't available,
# gracefully fall back to sqlite so the project can still run/tests can pass.
if DB_DEFAULT_ALIAS == "mysql":
    try:
        import MySQLdb  # noqa: F401
    except Exception:
        DB_DEFAULT_ALIAS = "sqlite"

SQLITE_DB_NAME = os.getenv("SQLITE_DB_NAME", str(BASE_DIR / "db.sqlite3"))

# MySQL Configuration
MYSQL_DB_NAME = os.getenv("MYSQL_DB_NAME", os.getenv("DB_NAME", "wasla"))
MYSQL_DB_USER = os.getenv("MYSQL_DB_USER", os.getenv("DB_USER", "root"))
MYSQL_DB_PASSWORD = os.getenv("MYSQL_DB_PASSWORD", os.getenv("DB_PASSWORD", ""))
MYSQL_DB_HOST = os.getenv("MYSQL_DB_HOST", os.getenv("DB_HOST", "127.0.0.1"))
MYSQL_DB_PORT = os.getenv("MYSQL_DB_PORT", os.getenv("DB_PORT", "3306"))

# PostgreSQL Configuration
PG_DB_NAME = os.getenv("DB_NAME", "wasla")
PG_DB_USER = os.getenv("DB_USER", "wasla_user")
PG_DB_PASSWORD = os.getenv("DB_PASSWORD", "")
PG_DB_HOST = os.getenv("DB_HOST", "127.0.0.1")
PG_DB_PORT = os.getenv("DB_PORT", "5432")

SQLITE_CONFIG = {
    "ENGINE": "django.db.backends.sqlite3",
    "NAME": SQLITE_DB_NAME,
}

MYSQL_CONFIG = {
    "ENGINE": "django.db.backends.mysql",
    "NAME": MYSQL_DB_NAME,
    "USER": MYSQL_DB_USER,
    "PASSWORD": MYSQL_DB_PASSWORD,
    "HOST": MYSQL_DB_HOST,
    "PORT": MYSQL_DB_PORT,
    "OPTIONS": {
        "charset": "utf8mb4",
    },
}

POSTGRESQL_CONFIG = {
    "ENGINE": "django.db.backends.postgresql",
    "NAME": PG_DB_NAME,
    "USER": PG_DB_USER,
    "PASSWORD": PG_DB_PASSWORD,
    "HOST": PG_DB_HOST,
    "PORT": PG_DB_PORT,
}

if DB_DEFAULT_ALIAS not in {"sqlite", "mysql", "postgresql"}:
    raise ImproperlyConfigured("DJANGO_DB_DEFAULT must be either 'sqlite', 'mysql', or 'postgresql'.")

# Select database based on DJANGO_DB_DEFAULT
if DB_DEFAULT_ALIAS == "sqlite":
    DEFAULT_DB = SQLITE_CONFIG
elif DB_DEFAULT_ALIAS == "postgresql":
    DEFAULT_DB = POSTGRESQL_CONFIG
else:
    DEFAULT_DB = MYSQL_CONFIG

DATABASES = {"default": DEFAULT_DB}

# Optional: expose other DB connections only when explicitly requested.
# Keeping them disabled by default avoids needing extra DB drivers (mysqlclient)
# for local development and automated tests.
if (os.getenv("DJANGO_ENABLE_EXTRA_DBS", "0") or "0") == "1":
    DATABASES.update(
        {
            "sqlite": SQLITE_CONFIG,
            "mysql": MYSQL_CONFIG,
            "postgresql": POSTGRESQL_CONFIG,
        }
    )


# Cache configuration
CACHE_TTL_DEFAULT = int(os.getenv("CACHE_TTL_DEFAULT", "300") or "300")
CACHE_TTL_SHORT = int(os.getenv("CACHE_TTL_SHORT", "60") or "60")
CACHE_TTL_LONG = int(os.getenv("CACHE_TTL_LONG", "900") or "900")
CACHE_KEY_PREFIX = os.getenv("CACHE_KEY_PREFIX", "wasla")
CACHE_USE_REDIS = _env_bool("CACHE_USE_REDIS", "0")
CACHE_REDIS_URL = os.getenv("CACHE_REDIS_URL", "redis://127.0.0.1:6379/1")

if CACHE_USE_REDIS:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": CACHE_REDIS_URL,
            "TIMEOUT": CACHE_TTL_DEFAULT,
            "KEY_PREFIX": CACHE_KEY_PREFIX,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "IGNORE_EXCEPTIONS": True,
            },
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "wasla-local-cache",
            "TIMEOUT": CACHE_TTL_DEFAULT,
            "KEY_PREFIX": CACHE_KEY_PREFIX,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# drf-spectacular OpenAPI/Swagger Configuration
SPECTACULAR_SETTINGS = {
    "TITLE": "WASLA API",
    "DESCRIPTION": "WASLA E-Commerce Platform API Documentation",
    "VERSION": os.getenv("APP_VERSION", "1.0.0"),
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],
    "RETRIEVE_SCHEMA_PATH": "/api/schema/",
    "SCHEMA_PATH_PREFIX": "/api/",
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "defaultModelsExpandDepth": 1,
        "defaultModelExpandDepth": 1,
        "displayOperationId": True,
        "layoutName": "BaseLayout",
        "syncUrl": True,
        "tryItOutEnabled": True,
    },
    "REDOC_UI_SETTINGS": {
        "expand-single-schema-field": True,
        "untrustedSpec": False,
        "hideDownloadButton": False,
    },
    "CONTACT": {
        "name": "WASLA Support",
        "url": "https://wasla.com/support",
        "email": "support@wasla.com",
    },
    "LICENSE": {
        "name": "MIT License",
        "url": "https://opensource.org/licenses/MIT",
    },
    "TAGS": [
        {
            "name": "Catalog / Variants",
            "description": "Product variant management including option groups, variant stock, and variant pricing resolution.",
        },
        {
            "name": "Catalog / Inventory",
            "description": "Inventory insights and stock movement tracking for merchant operations.",
        },
        {
            "name": "Cart",
            "description": "Cart operations for adding, updating, listing, and removing items.",
        },
        {
            "name": "Checkout",
            "description": "Checkout flow steps from address to shipping and order creation.",
        },
        {
            "name": "Orders",
            "description": "Order lifecycle, retrieval, and merchant order management operations.",
        },
        {
            "name": "Payments",
            "description": "Payment initiation, callbacks, and payment status operations.",
        },
        {
            "name": "Shipping",
            "description": "Shipping methods and shipment-related operations.",
        },
        {
            "name": "Settlements",
            "description": "Settlement calculations, payouts, and reconciliation operations.",
        },
        {
            "name": "Analytics",
            "description": "Store analytics, KPIs, and reporting endpoints.",
        },
        {
            "name": "AI",
            "description": "AI-assisted catalog, categorization, and search operations.",
        },
        {
            "name": "Imports",
            "description": "Bulk import validation and execution endpoints.",
        },
        {
            "name": "Exports",
            "description": "Data export endpoints for orders, invoices, and reports.",
        },
        {
            "name": "Themes",
            "description": "Storefront theme management and customization endpoints.",
        },
        {
            "name": "Reviews",
            "description": "Product review listing and moderation operations.",
        },
        {
            "name": "Subscriptions",
            "description": "Subscription plans, entitlements, and billing lifecycle operations.",
        },
        {
            "name": "Wallet",
            "description": "Wallet balance and wallet transaction operations.",
        },
    ],
}


# Auth redirects
LOGIN_URL = "/auth/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/"

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# Default language is Arabic (Saudi/Gulf first).
# Users can switch to English via /i18n/setlang/.
LANGUAGE_CODE = os.getenv("DJANGO_LANGUAGE_CODE", "ar").strip() or "ar"

LANGUAGES = [
    ("ar", "العربية"),
    ("en", "English"),
]

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# STATIC_URL = "static/"
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "Wasla <info@w-sala.com>")
SERVER_EMAIL = os.getenv("SERVER_EMAIL", "info@w-sala.com")

EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.hostinger.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "info@w-sala.com")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
STATIC_URL = "/static/"
# STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "static"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# STATIC_URL = "/static/"
# STATIC_ROOT = Path(os.getenv("DJANGO_STATIC_ROOT", str(BASE_DIR / "staticfiles")))
# STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []

# MEDIA_URL = "/media/"
# MEDIA_ROOT = Path(os.getenv("DJANGO_MEDIA_ROOT", str(BASE_DIR / "media")))

# --- AI / Visual Search (V1-P3) ---
AI_USE_CLIP_EMBEDDINGS = bool(int(os.environ.get('AI_USE_CLIP_EMBEDDINGS', '0')))
AI_CLIP_MODEL_NAME = os.environ.get('AI_CLIP_MODEL_NAME', 'openai/clip-vit-base-patch32')
AI_USE_CLIP_CATEGORIES = bool(int(os.environ.get('AI_USE_CLIP_CATEGORIES', '0')))
AI_CLIP_CATEGORY_LABELS = [x.strip() for x in os.environ.get('AI_CLIP_CATEGORY_LABELS', '').split(',') if x.strip()]

AI_USE_CLIP_MATERIALS = bool(int(os.environ.get('AI_USE_CLIP_MATERIALS', '0')))
AI_CLIP_MATERIAL_LABELS = [x.strip() for x in os.environ.get('AI_CLIP_MATERIAL_LABELS', '').split(',') if x.strip()]
AI_USE_CLIP_STYLES = bool(int(os.environ.get('AI_USE_CLIP_STYLES', '0')))
AI_CLIP_STYLE_LABELS = [x.strip() for x in os.environ.get('AI_CLIP_STYLE_LABELS', '').split(',') if x.strip()]

# Visual search defaults
AI_VISUAL_SEARCH_DEFAULT_TOP_N = int(os.environ.get('AI_VISUAL_SEARCH_DEFAULT_TOP_N', '12'))
AI_VISUAL_SEARCH_MAX_TOP_N = int(os.environ.get('AI_VISUAL_SEARCH_MAX_TOP_N', '24'))

AI_FAISS_INDEX_TYPE = os.environ.get('AI_FAISS_INDEX_TYPE', 'flat')  # flat|ivf
AI_FAISS_NLIST = int(os.environ.get('AI_FAISS_NLIST', '0') or 0)
AI_FAISS_NPROBE = int(os.environ.get('AI_FAISS_NPROBE', '0') or 0)

VISUAL_SEARCH_STT_PROVIDER = os.environ.get("VISUAL_SEARCH_STT_PROVIDER", "openai_whisper")
OPENAI_WHISPER_MODEL = os.environ.get("OPENAI_WHISPER_MODEL", "whisper-1")
GOOGLE_SPEECH_API_KEY = os.environ.get("GOOGLE_SPEECH_API_KEY", "")


# +# Reverse proxy / HTTPS (nginx)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = _env_bool("DJANGO_SECURE_SSL_REDIRECT", "1" if ENVIRONMENT == "production" else "0")
SESSION_COOKIE_SECURE = _env_bool("DJANGO_SESSION_COOKIE_SECURE", "1" if ENVIRONMENT == "production" else "0")
CSRF_COOKIE_SECURE = _env_bool("DJANGO_CSRF_COOKIE_SECURE", "1" if ENVIRONMENT == "production" else "0")
SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_SECURE_HSTS_SECONDS", "31536000" if ENVIRONMENT == "production" else "0") or "0")
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", "1" if ENVIRONMENT == "production" else "0")
SECURE_HSTS_PRELOAD = _env_bool("DJANGO_SECURE_HSTS_PRELOAD", "1" if ENVIRONMENT == "production" else "0")
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"


# ==============================================================================
# CELERY CONFIGURATION
# ==============================================================================

# Celery Broker and Backend Configuration
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")

# Celery Message Serialization
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

# Celery Timezone Configuration
CELERY_TIMEZONE = "UTC"
CELERY_ENABLE_UTC = True

# Celery Task Result Configuration
CELERY_RESULT_EXPIRES = 3600  # Results expire after 1 hour
CELERY_TASK_TRACK_STARTED = True  # Track when tasks start
CELERY_TASK_TIME_LIMIT = 30 * 60  # Task timeout: 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # Soft timeout: 25 minutes

# Celery Worker Configuration
CELERY_WORKER_PREFETCH_MULTIPLIER = 4  # Number of tasks to prefetch
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000  # Restart worker after N tasks

# Celery Beat Configuration
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"  # Use DB for schedule persistence

# Task Routes (optional - for task prioritization)
CELERY_TASK_ROUTES = {
    "apps.settlements.tasks.*": {"queue": "settlements"},
    "apps.notifications.tasks.*": {"queue": "notifications"},
}

# Task Priority Configuration (optional)
CELERY_TASK_DEFAULT_PRIORITY = 5
CELERY_TASK_INHERIT_PARENT_PRIORITY = True

# ==============================================================================
# SETTLEMENT AUTOMATION CONFIGURATION
# ==============================================================================

# Settlement SLA Policy: Hours before an order is eligible for settlement
SETTLEMENT_DELAY_HOURS = int(os.getenv("SETTLEMENT_DELAY_HOURS", "24"))

# Settlement batch processing configuration
SETTLEMENT_BATCH_SIZE = int(os.getenv("SETTLEMENT_BATCH_SIZE", "100"))

# Maximum number of orders to batch process in a single run
SETTLEMENT_BATCH_MAX_ORDERS = int(os.getenv("SETTLEMENT_BATCH_MAX_ORDERS", "1000"))

# Settlement batch processing timeout (minutes)
SETTLEMENT_BATCH_TIMEOUT_MINUTES = int(os.getenv("SETTLEMENT_BATCH_TIMEOUT_MINUTES", "30"))

# Enable auto-approval of settlements (default: False - manual approval required)
SETTLEMENT_AUTO_APPROVE = _env_bool("SETTLEMENT_AUTO_APPROVE", "0")

# Reconciliation lookback window (days)
SETTLEMENT_RECONCILIATION_LOOKBACK_DAYS = int(os.getenv("SETTLEMENT_RECONCILIATION_LOOKBACK_DAYS", "7"))

# Settlement audit log retention (days)
SETTLEMENT_AUDIT_LOG_RETENTION_DAYS = int(os.getenv("SETTLEMENT_AUDIT_LOG_RETENTION_DAYS", "90"))

# Enable detailed settlement logging
SETTLEMENT_DETAILED_LOGGING = _env_bool("SETTLEMENT_DETAILED_LOGGING", "1")

# Settlement notification recipients (comma-separated emails)
SETTLEMENT_NOTIFICATION_EMAILS = _env_list("SETTLEMENT_NOTIFICATION_EMAILS", [])

# Enable settlement processing
SETTLEMENT_PROCESSING_ENABLED = _env_bool("SETTLEMENT_PROCESSING_ENABLED", "1")


# Performance observability
PERFORMANCE_SLOW_THRESHOLD_MS = float(os.getenv("PERFORMANCE_SLOW_THRESHOLD_MS", "500") or "500")
PERFORMANCE_LOG_PERSIST_ENABLED = _env_bool("PERFORMANCE_LOG_PERSIST_ENABLED", "1")
PERFORMANCE_SLOW_QUERY_THRESHOLD_MS = float(os.getenv("PERFORMANCE_SLOW_QUERY_THRESHOLD_MS", "250") or "250")
OBS_LOG_LEVEL = os.getenv("OBS_LOG_LEVEL", "INFO")


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": "apps.observability.logging.JSONFormatter",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        }
    },
    "loggers": {
        "wasla.request": {
            "handlers": ["console"],
            "level": os.getenv("WASLA_REQUEST_LOG_LEVEL", OBS_LOG_LEVEL),
            "propagate": False,
        },
        "wasla.performance": {
            "handlers": ["console"],
            "level": os.getenv("WASLA_PERFORMANCE_LOG_LEVEL", OBS_LOG_LEVEL),
            "propagate": False,
        },
    },
}