"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"

ALLOWED_HOSTS = [h.strip() for h in os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",") if h.strip()]

def _env_bool(name: str, default: str = "0") -> bool:
    return os.getenv(name, default).strip().lower() in ("1", "true", "yes", "on")


def _env_list(name: str, default: list[str] | None = None) -> list[str]:
    raw = os.getenv(name, "")
    if raw.strip():
        return [item.strip() for item in raw.split(",") if item.strip()]
    return list(default or [])


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure--cop!lr6o*&sny4$%3&-=)l18w7-lf+7$a8itl+q%qz!4p1yll",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DJANGO_DEBUG", "1")
ENVIRONMENT = os.getenv("ENVIRONMENT", "development").strip().lower() or "development"
TEST_OTP_CODE = os.getenv("TEST_OTP_CODE", "12345").strip() or "12345"

WASSLA_BASE_DOMAIN = os.getenv("WASSLA_BASE_DOMAIN", "w-sala.com").strip().lower() or "w-sala.com"

ALLOWED_HOSTS = _env_list(
    "DJANGO_ALLOWED_HOSTS",
    default=[
        "localhost",
        "127.0.0.1",
        "[::1]",
        WASSLA_BASE_DOMAIN,
        f"www.{WASSLA_BASE_DOMAIN}",
        "76.13.143.149",
    ],
)

CSRF_TRUSTED_ORIGINS = _env_list("DJANGO_CSRF_TRUSTED_ORIGINS", default=[])

# Custom domains (multi-tenant mapping)
CUSTOM_DOMAIN_SERVER_IP = os.getenv("CUSTOM_DOMAIN_SERVER_IP", "").strip()
CUSTOM_DOMAIN_CNAME_TARGET = os.getenv("CUSTOM_DOMAIN_CNAME_TARGET", "").strip()
CUSTOM_DOMAIN_BLOCKED_DOMAINS = _env_list("CUSTOM_DOMAIN_BLOCKED_DOMAINS", default=[WASSLA_BASE_DOMAIN])
CUSTOM_DOMAIN_VERIFICATION_PATH_PREFIX = os.getenv(
    "CUSTOM_DOMAIN_VERIFICATION_PATH_PREFIX",
    "/.well-known/wassla-domain-verification",
).strip()
CUSTOM_DOMAIN_HTTP_TIMEOUT_SECONDS = int(os.getenv("CUSTOM_DOMAIN_HTTP_TIMEOUT_SECONDS", "5") or "5")
CUSTOM_DOMAIN_VERIFY_MIN_INTERVAL_SECONDS = int(
    os.getenv("CUSTOM_DOMAIN_VERIFY_MIN_INTERVAL_SECONDS", "30") or "30"
)
CUSTOM_DOMAIN_DNS_CACHE_SECONDS = int(os.getenv("CUSTOM_DOMAIN_DNS_CACHE_SECONDS", "300") or "300")
CUSTOM_DOMAIN_CACHE_SECONDS = int(os.getenv("CUSTOM_DOMAIN_CACHE_SECONDS", "300") or "300")

# SSL/Certbot
CUSTOM_DOMAIN_SSL_ENABLED = _env_bool("CUSTOM_DOMAIN_SSL_ENABLED", "0")
CUSTOM_DOMAIN_CERTBOT_CMD = os.getenv("CUSTOM_DOMAIN_CERTBOT_CMD", "certbot").strip() or "certbot"
CUSTOM_DOMAIN_CERTBOT_EMAIL = os.getenv("CUSTOM_DOMAIN_CERTBOT_EMAIL", "").strip()
CUSTOM_DOMAIN_CERTBOT_MODE = os.getenv("CUSTOM_DOMAIN_CERTBOT_MODE", "http-01").strip() or "http-01"
CUSTOM_DOMAIN_CERTBOT_WEBROOT = os.getenv(
    "CUSTOM_DOMAIN_CERTBOT_WEBROOT",
    "/var/www/certbot",
).strip()
CUSTOM_DOMAIN_CERTBOT_DNS_AUTH_HOOK = os.getenv("CUSTOM_DOMAIN_CERTBOT_DNS_AUTH_HOOK", "").strip()
CUSTOM_DOMAIN_CERTBOT_DNS_CLEANUP_HOOK = os.getenv("CUSTOM_DOMAIN_CERTBOT_DNS_CLEANUP_HOOK", "").strip()
CUSTOM_DOMAIN_CERTS_DIR = os.getenv("CUSTOM_DOMAIN_CERTS_DIR", "/etc/letsencrypt/live").strip()

# Nginx dynamic config
CUSTOM_DOMAIN_NGINX_ENABLED = _env_bool("CUSTOM_DOMAIN_NGINX_ENABLED", "0")
CUSTOM_DOMAIN_NGINX_DOMAINS_DIR = os.getenv(
    "CUSTOM_DOMAIN_NGINX_DOMAINS_DIR",
    "/etc/nginx/conf.d/wasla_domains",
).strip()
CUSTOM_DOMAIN_NGINX_UPSTREAM = os.getenv(
    "CUSTOM_DOMAIN_NGINX_UPSTREAM",
    "http://127.0.0.1:8000",
).strip()
CUSTOM_DOMAIN_NGINX_TEST_CMD = os.getenv("CUSTOM_DOMAIN_NGINX_TEST_CMD", "nginx -t").strip()
CUSTOM_DOMAIN_NGINX_RELOAD_CMD = os.getenv("CUSTOM_DOMAIN_NGINX_RELOAD_CMD", "systemctl reload nginx").strip()
CUSTOM_DOMAIN_FORCE_HTTPS = _env_bool("CUSTOM_DOMAIN_FORCE_HTTPS", "0")
CUSTOM_DOMAIN_NGINX_RELOAD_IN_REQUEST = _env_bool("CUSTOM_DOMAIN_NGINX_RELOAD_IN_REQUEST", "0")
DOMAIN_PROVISIONING_MODE = os.getenv("DOMAIN_PROVISIONING_MODE", "manual").strip().lower() or "manual"

NGINX_TEMPLATE_DIR = os.getenv("NGINX_TEMPLATE_DIR", "infrastructure/nginx").strip() or "infrastructure/nginx"
NGINX_DOMAIN_TEMPLATE = os.getenv("NGINX_DOMAIN_TEMPLATE", "domain.conf.j2").strip() or "domain.conf.j2"



# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
     "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "accounts.apps.AccountsConfig",
    "sms.apps.SmsConfig",
    "notifications.apps.NotificationsConfig",
    "tenants.apps.TenantsConfig",
    "catalog.apps.CatalogConfig",
    "customers.apps.CustomerConfig",
    "cart.apps.CartConfig",
    "checkout.apps.CheckoutConfig",
    "orders.apps.OrderConfig",
    "payments.apps.PaymentConfig",
    "imports.apps.ImportsConfig",
    "themes.apps.ThemesConfig",
    "exports.apps.ExportsConfig",
    "settlements.apps.SettlementsConfig",
    "ai.apps.AiConfig",
    "domains.apps.DomainsConfig",
    "observability.apps.ObservabilityConfig",
    "security.apps.SecurityConfig",
    "analytics.apps.AnalyticsConfig",
    "plugins.apps.PluginsConfig",
    "reviews.apps.ReviewsConfig",
    "shipping.apps.ShippingConfig",
    "subscriptions.apps.SubscriptionConfig",
    "wallet.apps.WalletConfig",
    "emails.apps.EmailsConfig",
    "webhooks.apps.WebhooksConfig",
    "system.apps.SystemConfig",
    "stores.apps.StoresConfig"
    
    
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "tenants.middleware.TenantMiddleware",
    "tenants.middleware.TenantLocaleMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

DB_ENGINE = os.getenv("DB_ENGINE", os.getenv("DJANGO_DB_ENGINE", "django.db.backends.sqlite3")).strip()
if DB_ENGINE == "django.db.backends.postgresql":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME", os.getenv("POSTGRES_DB", "wasla")),
            "USER": os.getenv("DB_USER", os.getenv("POSTGRES_USER", "wasla")),
            "PASSWORD": os.getenv("DB_PASSWORD", os.getenv("POSTGRES_PASSWORD", "")),
            "HOST": os.getenv("DB_HOST", os.getenv("POSTGRES_HOST", "127.0.0.1")),
            "PORT": os.getenv("DB_PORT", os.getenv("POSTGRES_PORT", "5432")),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}


# Auth redirects
LOGIN_URL = "/auth/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/"

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# Default language is Arabic (Saudi/Gulf first).
# Users can switch to English via /i18n/setlang/.
LANGUAGE_CODE = "ar"

LANGUAGES = [
    ("ar", "العربية"),
    ("en", "English"),
]

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# STATIC_URL = "static/"
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "Wasla <info@w-sala.com>")
SERVER_EMAIL = os.getenv("SERVER_EMAIL", "info@w-sala.com")

EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.hostinger.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "info@w-sala.com")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "YazYaz@2030")


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []
STATIC_ROOT = Path(os.getenv("DJANGO_STATIC_ROOT", str(BASE_DIR / "staticfiles")))

# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "media"

MEDIA_URL = "/media/"
MEDIA_ROOT = Path(os.getenv("DJANGO_MEDIA_ROOT", str(BASE_DIR / "media")))

# --- AI / Visual Search (V1-P3) ---
AI_USE_CLIP_EMBEDDINGS = bool(int(os.environ.get('AI_USE_CLIP_EMBEDDINGS', '0')))
AI_CLIP_MODEL_NAME = os.environ.get('AI_CLIP_MODEL_NAME', 'openai/clip-vit-base-patch32')
AI_USE_CLIP_CATEGORIES = bool(int(os.environ.get('AI_USE_CLIP_CATEGORIES', '0')))
AI_CLIP_CATEGORY_LABELS = [x.strip() for x in os.environ.get('AI_CLIP_CATEGORY_LABELS', '').split(',') if x.strip()]

AI_USE_CLIP_MATERIALS = bool(int(os.environ.get('AI_USE_CLIP_MATERIALS', '0')))
AI_CLIP_MATERIAL_LABELS = [x.strip() for x in os.environ.get('AI_CLIP_MATERIAL_LABELS', '').split(',') if x.strip()]
AI_USE_CLIP_STYLES = bool(int(os.environ.get('AI_USE_CLIP_STYLES', '0')))
AI_CLIP_STYLE_LABELS = [x.strip() for x in os.environ.get('AI_CLIP_STYLE_LABELS', '').split(',') if x.strip()]

# Visual search defaults
AI_VISUAL_SEARCH_DEFAULT_TOP_N = int(os.environ.get('AI_VISUAL_SEARCH_DEFAULT_TOP_N', '12'))
AI_VISUAL_SEARCH_MAX_TOP_N = int(os.environ.get('AI_VISUAL_SEARCH_MAX_TOP_N', '24'))

AI_FAISS_INDEX_TYPE = os.environ.get('AI_FAISS_INDEX_TYPE', 'flat')  # flat|ivf
AI_FAISS_NLIST = int(os.environ.get('AI_FAISS_NLIST', '0') or 0)
AI_FAISS_NPROBE = int(os.environ.get('AI_FAISS_NPROBE', '0') or 0)


# +# Reverse proxy / HTTPS (nginx)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = _env_bool("DJANGO_SECURE_SSL_REDIRECT", "0")
SESSION_COOKIE_SECURE = _env_bool("DJANGO_SESSION_COOKIE_SECURE", "0")
CSRF_COOKIE_SECURE = _env_bool("DJANGO_CSRF_COOKIE_SECURE", "0")
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
