# Generated by Django 5.1.15 on 2026-02-12 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_country", models.CharField(default="+966", max_length=8)),
                ("phone_number", models.CharField(blank=True, max_length=32)),
                ("country", models.CharField(blank=True, max_length=32)),
                ("legal_entity", models.CharField(blank=True, max_length=64)),
                ("has_existing_business", models.CharField(blank=True, max_length=16)),
                ("selling_channel", models.CharField(blank=True, max_length=64)),
                ("category_main", models.CharField(blank=True, max_length=128)),
                ("category_sub", models.CharField(blank=True, max_length=128)),
                ("persona_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
