# Generated by Django 5.1.15 on 2026-02-06 00:00

from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantSmsSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(choices=[("console", "Console (dev)"), ("taqnyat", "Taqnyat")], default="console", max_length=32)),
                ("is_enabled", models.BooleanField(default=False)),
                ("sender_name", models.CharField(blank=True, default="", max_length=50)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_settings",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["provider", "is_enabled"], name="sms_tenants_provide_bb9a27_idx"),
                    models.Index(fields=["updated_at"], name="sms_tenants_updated_927dd4_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SmsMessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="", max_length=32)),
                ("sender", models.CharField(default="", max_length=50)),
                ("body", models.TextField()),
                ("recipients", models.JSONField(blank=True, default=list)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("sent", "Sent"), ("scheduled", "Scheduled"), ("failed", "Failed")], default="queued", max_length=16)),
                ("provider_message_id", models.CharField(blank=True, default="", max_length=128)),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_logs",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tenant", "created_at"], name="sms_smsmess_tenant__4cb5a0_idx"),
                    models.Index(fields=["provider", "created_at"], name="sms_smsmess_provide_9b0134_idx"),
                    models.Index(fields=["status", "created_at"], name="sms_smsmess_status_94d86f_idx"),
                ],
            },
        ),
    ]
