# Generated by Django 5.2.11 on 2026-03-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0002_add_platform_default_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="is_default_published",
            field=models.BooleanField(
                default=False,
                help_text="Whether the default storefront has been published.",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="default_published_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="When the default storefront was published.",
            ),
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(
                fields=["is_default_published", "created_at"],
                name="stores_stor_is_def_0dd8fb_idx",
            ),
        ),
    ]
