# Generated by Django 5.2.11 on 2026-03-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0003_add_storefront_publish_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="is_default_published",
            field=models.BooleanField(
                default=False,
                db_default=False,
                help_text="Whether the default storefront has been published.",
            ),
        ),
    ]
