# Generated by Django 5.2.11 on 2026-03-01 10:49

import apps.tenants.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, unique=True)),
                ('module', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['module', 'code'], name='tenants_per_module_deb6d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('subdomain', models.CharField(blank=True, default='', max_length=100)),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('language', models.CharField(default='ar', max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.tenants.models.tenant_logo_upload_to)),
                ('primary_color', models.CharField(blank=True, default='', max_length=7)),
                ('secondary_color', models.CharField(blank=True, default='', max_length=7)),
                ('setup_step', models.PositiveSmallIntegerField(default=1)),
                ('setup_completed', models.BooleanField(default=False)),
                ('setup_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_tenants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreShippingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfillment_mode', models.CharField(choices=[('pickup', 'Pickup'), ('manual_delivery', 'Manual delivery'), ('carrier', 'Carrier (Phase 2)')], default='pickup', max_length=20)),
                ('origin_city', models.CharField(blank=True, default='', max_length=100)),
                ('delivery_fee_flat', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_settings', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='StoreProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_info_completed', models.BooleanField(default=False)),
                ('setup_step', models.PositiveSmallIntegerField(default=1)),
                ('is_setup_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_store_profile', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_profile', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='StorePaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('manual', 'Manual (offline/COD)'), ('dummy', 'Dummy (testing)'), ('gateway', 'Gateway (Phase 2)')], default='manual', max_length=20)),
                ('provider_name', models.CharField(blank=True, default='', max_length=50)),
                ('merchant_key', models.CharField(blank=True, default='', max_length=255)),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_settings', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='StoreDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('cert_requested', 'Certificate Requested'), ('cert_issued', 'Certificate Issued'), ('active', 'Active'), ('degraded', 'Degraded'), ('failed', 'Failed')], db_index=True, default='pending_verification', max_length=25)),
                ('verification_method', models.CharField(choices=[('dns_txt', 'DNS TXT Record'), ('dns_cname', 'DNS CNAME Record')], default='dns_txt', max_length=20)),
                ('verification_token', models.CharField(blank=True, default='', max_length=256, unique=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('cert_provider', models.CharField(choices=[('lets_encrypt', "Let's Encrypt")], default='lets_encrypt', max_length=25)),
                ('cert_issued_at', models.DateTimeField(blank=True, null=True)),
                ('cert_expires_at', models.DateTimeField(blank=True, null=True)),
                ('ssl_cert_path', models.TextField(blank=True, default='')),
                ('ssl_key_path', models.TextField(blank=True, default='')),
                ('last_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('retry_count', models.IntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_domains', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('actor', models.CharField(blank=True, default='system', max_length=100)),
                ('details', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('staff', 'Staff'), ('read_only', 'Read-only')], default='owner', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('staff', 'Staff'), ('read_only', 'Read-only')], max_length=20)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='tenants.permission')),
            ],
            options={
                'indexes': [models.Index(fields=['role'], name='tenants_rol_role_e81812_idx')],
                'constraints': [models.UniqueConstraint(fields=('role', 'permission'), name='uq_role_permission_role_permission')],
            },
        ),
        migrations.CreateModel(
            name='DomainAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status Changed'), ('verified', 'Verified'), ('cert_requested', 'Certificate Requested'), ('cert_issued', 'Certificate Issued'), ('activated', 'Activated'), ('failed', 'Failed'), ('rechecked', 'Rechecked'), ('deleted', 'Deleted')], max_length=50)),
                ('previous_status', models.CharField(blank=True, default='', max_length=25)),
                ('new_status', models.CharField(blank=True, default='', max_length=25)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('performed_by', models.CharField(blank=True, default='system', help_text="User email or 'system' for automated tasks", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.storedomain')),
            ],
            options={
                'verbose_name': 'Domain Audit Log',
                'verbose_name_plural': 'Domain Audit Logs',
                'indexes': [models.Index(fields=['domain', 'created_at'], name='tenants_dom_domain__fb50c9_idx'), models.Index(fields=['action', 'created_at'], name='tenants_dom_action_8a1272_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['is_active'], name='tenants_ten_is_acti_8f654a_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['is_published'], name='tenants_tenant_is_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='storeshippingsettings',
            index=models.Index(fields=['fulfillment_mode', 'is_enabled'], name='tenants_sto_fulfill_0605c9_idx'),
        ),
        migrations.AddIndex(
            model_name='storeprofile',
            index=models.Index(fields=['store_info_completed'], name='tenants_sto_store_i_26bbca_idx'),
        ),
        migrations.AddIndex(
            model_name='storeprofile',
            index=models.Index(fields=['setup_step'], name='tenants_sto_setup_s_b0b1e4_idx'),
        ),
        migrations.AddIndex(
            model_name='storeprofile',
            index=models.Index(fields=['is_setup_complete'], name='tenants_sto_is_setu_54a21b_idx'),
        ),
        migrations.AddIndex(
            model_name='storepaymentsettings',
            index=models.Index(fields=['mode', 'is_enabled'], name='tenants_sto_mode_0295ee_idx'),
        ),
        migrations.AddIndex(
            model_name='storedomain',
            index=models.Index(fields=['domain'], name='storedomain_domain_idx'),
        ),
        migrations.AddIndex(
            model_name='storedomain',
            index=models.Index(fields=['tenant', 'status'], name='storedomain_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='storedomain',
            index=models.Index(fields=['status', 'next_retry_at'], name='storedomain_status_retry_idx'),
        ),
        migrations.AddIndex(
            model_name='storedomain',
            index=models.Index(fields=['cert_expires_at'], name='storedomain_cert_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantauditlog',
            index=models.Index(fields=['tenant', 'action'], name='tenants_ten_tenant__3c5f49_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantauditlog',
            index=models.Index(fields=['created_at'], name='tenants_ten_created_1f46d6_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['tenant', 'role', 'is_active'], name='tenants_ten_tenant__f04c06_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['user', 'role', 'is_active'], name='tenants_ten_user_id_66b6e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantmembership',
            constraint=models.UniqueConstraint(fields=('tenant', 'user'), name='uq_tenant_membership_tenant_user'),
        ),
        migrations.AddConstraint(
            model_name='tenantmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'owner'), ('is_active', True)), fields=('tenant',), name='uq_tenant_membership_one_owner_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='tenantmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'owner'), ('is_active', True)), fields=('user',), name='uq_tenant_membership_one_owned_store_per_user'),
        ),
    ]
