# Generated by Django 5.1.15 on 2026-02-06 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_create_default_tenant"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                (
                    "actor",
                    models.CharField(blank=True, default="system", max_length=100),
                ),
                ("details", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "action"],
                        name="tenants_ten_tenant__3c5f49_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="tenants_ten_created_1f46d6_idx"
                    ),
                ],
            },
        ),
    ]
