# Generated by Django 5.1.15 on 2026-02-06 11:15

import apps.tenants.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from apps import tenants


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_tenantauditlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.tenants.models.tenant_logo_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="primary_color",
            field=models.CharField(blank=True, default="", max_length=7),
        ),
        migrations.AddField(
            model_name="tenant",
            name="secondary_color",
            field=models.CharField(blank=True, default="", max_length=7),
        ),
        migrations.AddField(
            model_name="tenant",
            name="setup_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenant",
            name="setup_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="setup_step",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="currency",
            field=models.CharField(default="SAR", max_length=10),
        ),
        migrations.CreateModel(
            name="TenantMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("staff", "Staff"),
                            ("read_only", "Read-only"),
                        ],
                        default="owner",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "role", "is_active"],
                        name="tenants_ten_tenant__f04c06_idx",
                    ),
                    models.Index(
                        fields=["user", "role", "is_active"],
                        name="tenants_ten_user_id_66b6e4_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "user"),
                        name="uq_tenant_membership_tenant_user",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("role", "owner"), ("is_active", True)),
                        fields=("tenant",),
                        name="uq_tenant_membership_one_owner_per_tenant",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("role", "owner"), ("is_active", True)),
                        fields=("user",),
                        name="uq_tenant_membership_one_owned_store_per_user",
                    ),
                ],
            },
        ),
    ]
