# Generated by Codex on 2026-02-25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0012_tenant_activated_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=120, unique=True)),
                ("module", models.CharField(max_length=60)),
                ("description", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "indexes": [models.Index(fields=["module", "code"], name="tenants_per_module_6918be_idx")],
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Owner"), ("admin", "Admin"), ("staff", "Staff"), ("read_only", "Read-only")],
                        max_length=20,
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="role_permissions", to="tenants.permission"),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["role"], name="tenants_rol_role_7a8720_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("role", "permission"), name="uq_role_permission_role_permission")
                ],
            },
        ),
    ]
