# Generated by Django 5.2.11 on 2026-03-01 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_country', models.CharField(default='+966', max_length=8)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('country', models.CharField(blank=True, max_length=32)),
                ('legal_entity', models.CharField(blank=True, max_length=64)),
                ('has_existing_business', models.CharField(blank=True, max_length=16)),
                ('selling_channel', models.CharField(blank=True, max_length=64)),
                ('category_main', models.CharField(blank=True, max_length=128)),
                ('category_sub', models.CharField(blank=True, max_length=128)),
                ('persona_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
