# Generated by Codex on 2026-02-28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="TOTPSecret",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("secret", models.CharField(max_length=32, help_text="Base32-encoded TOTP secret")),
                ("is_active", models.BooleanField(default=False, help_text="Whether 2FA is enabled")),
                ("verified_at", models.DateTimeField(blank=True, null=True, help_text="When user verified 2FA setup")),
                ("backup_codes", models.TextField(help_text="JSON list of encrypted backup codes [consumed codes filtered out]")),
                ("failed_attempts", models.IntegerField(default=0, help_text="Failed OTP verification attempts")),
                ("last_failed_at", models.DateTimeField(blank=True, null=True, help_text="Last failed OTP attempt timestamp")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="totp_secret", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "accounts_totp_secret",
                "indexes": [
                    models.Index(fields=["user", "is_active"], name="accounts_totp_user_active_idx"),
                ],
            },
        ),
    ]

