# Generated by Django 5.1.15 on 2026-02-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_orders_monthly",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Max orders per calendar month for a store. Leave empty for unlimited.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_products",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Max products allowed for a store. Leave empty for unlimited.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_staff_users",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Max staff users allowed for a store. Leave empty for unlimited.",
                null=True,
            ),
        ),
    ]
