# Generated by Django 5.1.15 on 2026-02-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="importjob",
            new_name="imports_imp_store_i_229e7c_idx",
            old_name="imports_impo_store_c0d915_idx",
        ),
        migrations.RenameIndex(
            model_name="importjob",
            new_name="imports_imp_store_i_cc737b_idx",
            old_name="imports_impo_store_3b8f23_idx",
        ),
        migrations.RenameIndex(
            model_name="importrowerror",
            new_name="imports_imp_import__96f841_idx",
            old_name="imports_impo_import_4e2b7f_idx",
        ),
    ]
