# Generated by Django 5.2.11 on 2026-03-01 10:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('carrier', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='ready', max_length=20)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=100)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Zone name (e.g., 'GCC Countries', 'Saudi Arabia')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Zone description and coverage areas')),
                ('countries', models.CharField(help_text="Comma-separated country codes (e.g., 'SA,AE,KW,QA')", max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this zone')),
                ('priority', models.IntegerField(default=0, help_text='Priority for matching (higher number = higher priority)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(help_text='Store this zone belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='shipping_zones', to='stores.store')),
            ],
            options={
                'verbose_name': 'Shipping Zone',
                'verbose_name_plural': 'Shipping Zones',
                'db_table': 'shipping_zone',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Rate name (e.g., 'Standard', 'Express')", max_length=100)),
                ('rate_type', models.CharField(choices=[('flat', 'Flat Rate'), ('weight', 'Weight-Based (per kg)')], default='flat', help_text='How shipping is calculated', max_length=20)),
                ('base_rate', models.DecimalField(decimal_places=2, help_text='Base shipping cost or cost per kg', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_weight', models.DecimalField(decimal_places=2, default=0, help_text='Minimum weight for this rate (kg)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum weight for this rate (kg), null = no limit', max_digits=10, null=True)),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Order amount for free shipping (e.g., 100 SAR)', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this rate')),
                ('priority', models.IntegerField(default=0, help_text='Priority for matching (higher = first checked)')),
                ('estimated_days', models.IntegerField(blank=True, help_text='Estimated delivery days', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(help_text='Zone this rate applies to', on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rates', to='shipping.shippingzone')),
            ],
            options={
                'verbose_name': 'Shipping Rate',
                'verbose_name_plural': 'Shipping Rates',
                'db_table': 'shipping_rate',
                'ordering': ['-priority', 'min_weight'],
            },
        ),
        migrations.AddIndex(
            model_name='shippingzone',
            index=models.Index(fields=['store', 'is_active'], name='shipping_zo_store_i_9e649f_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingzone',
            index=models.Index(fields=['priority'], name='shipping_zo_priorit_51363a_idx'),
        ),
        migrations.AddConstraint(
            model_name='shippingzone',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='unique_zone_per_store'),
        ),
        migrations.AddIndex(
            model_name='shippingrate',
            index=models.Index(fields=['zone', 'is_active'], name='shipping_ra_zone_id_9b0e34_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingrate',
            index=models.Index(fields=['rate_type', 'priority'], name='shipping_ra_rate_ty_31e31d_idx'),
        ),
    ]
