# Generated by Django 5.2.11 on 2026-02-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="tenant_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
