# Generated by Codex on 2026-02-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0002_shipping_zones_and_rates"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="notification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

