# Generated by Django 5.2.11 on 2026-02-16 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_product_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField(db_index=True)),
                ('vector_hash', models.CharField(blank=True, default='', max_length=64)),
                ('similarity_hint', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visual_embedding', to='catalog.product')),
            ],
            options={
                'indexes': [models.Index(fields=['store_id', 'similarity_hint'], name='vs_store_similarity_idx'), models.Index(fields=['store_id', 'updated_at'], name='vs_store_updated_idx')],
                'constraints': [models.UniqueConstraint(fields=('store_id', 'product'), name='uq_visual_embedding_store_product')],
            },
        ),
    ]
