# Generated by Django 5.2.11 on 2026-03-01 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(max_length=20)),
                ('provider', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('required_feature', models.CharField(default='plugins', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('dependencies', models.ManyToManyField(blank=True, related_name='dependents', to='plugins.plugin')),
            ],
        ),
        migrations.CreateModel(
            name='InstalledPlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('store_id', models.IntegerField()),
                ('status', models.CharField(choices=[('installed', 'Installed'), ('active', 'Active'), ('disabled', 'Disabled'), ('uninstalled', 'Uninstalled')], max_length=20)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plugins.plugin')),
            ],
            options={
                'unique_together': {('plugin', 'store_id')},
            },
        ),
        migrations.CreateModel(
            name='PluginActivationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('store_id', models.IntegerField(db_index=True)),
                ('action', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], max_length=20)),
                ('actor_user_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('installed_plugin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activation_logs', to='plugins.installedplugin')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activation_logs', to='plugins.plugin')),
            ],
            options={
                'indexes': [models.Index(fields=['store_id', 'created_at'], name='plugins_plu_store_i_469394_idx'), models.Index(fields=['tenant_id', 'created_at'], name='plugins_plu_tenant__f3480f_idx'), models.Index(fields=['plugin', 'created_at'], name='plugins_plu_plugin__f22c03_idx')],
            },
        ),
        migrations.CreateModel(
            name='PluginEventDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('event_key', models.CharField(max_length=120)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('delivered', 'Delivered'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('error_message', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installed_plugin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_deliveries', to='plugins.installedplugin')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_deliveries', to='plugins.plugin')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'event_key', 'created_at'], name='plugins_plu_tenant__61ce62_idx'), models.Index(fields=['plugin', 'status', 'created_at'], name='plugins_plu_plugin__d39731_idx')],
            },
        ),
        migrations.CreateModel(
            name='PluginEventSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('event_key', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installed_plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_subscriptions', to='plugins.installedplugin')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'event_key'], name='plugins_plu_tenant__54713e_idx')],
                'constraints': [models.UniqueConstraint(fields=('installed_plugin', 'event_key'), name='uq_plugin_event_subscription')],
            },
        ),
        migrations.CreateModel(
            name='PluginPermissionScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_code', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_scopes', to='plugins.plugin')),
            ],
            options={
                'indexes': [models.Index(fields=['scope_code'], name='plugins_plu_scope_c_281a8f_idx')],
                'constraints': [models.UniqueConstraint(fields=('plugin', 'scope_code'), name='uq_plugin_scope_code')],
            },
        ),
        migrations.CreateModel(
            name='PluginRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_key', models.CharField(max_length=120, unique=True)),
                ('entrypoint', models.CharField(max_length=255)),
                ('min_core_version', models.CharField(default='0.0.0', max_length=32)),
                ('max_core_version', models.CharField(blank=True, default='', max_length=32)),
                ('isolation_mode', models.CharField(choices=[('process', 'Process'), ('sandbox', 'Sandbox')], default='sandbox', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plugin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='plugins.plugin')),
            ],
            options={
                'indexes': [models.Index(fields=['plugin_key'], name='plugins_plu_plugin__0603eb_idx'), models.Index(fields=['verified'], name='plugins_plu_verifie_64240e_idx')],
            },
        ),
    ]
