# Generated by Django 5.1.15 on 2026-02-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_payment_provider_settings"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="paymentevent",
            new_name="payments_pa_provide_21daef_idx",
            old_name="payments_pa_provider_9a3f7a_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentevent",
            new_name="payments_pa_receive_e166c1_idx",
            old_name="payments_pa_received_7c69c2_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentintent",
            new_name="payments_pa_store_i_c96fb3_idx",
            old_name="payments_pa_store_i_5f64f3_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentintent",
            new_name="payments_pa_provide_62d79e_idx",
            old_name="payments_pa_provider_6bde6f_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentprovidersettings",
            new_name="payments_pa_tenant__c25732_idx",
            old_name="payments_pa_tenant__1f443c_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentprovidersettings",
            new_name="payments_pa_provide_f6d35e_idx",
            old_name="payments_pa_provid_66e7d2_idx",
        ),
    ]
