# Generated by Django 6.0.2 on 2026-02-17 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_refund_tracking_settlement'),
        ('payments', '0004_rename_payments_pa_provider_9a3f7a_idx_payments_pa_provide_21daef_idx_and_more'),
    ]

    operations = [
    ]
