# Generated by Django 5.1.15 on 2026-02-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="aiproductembedding",
            new_name="ai_aiproduc_store_i_ca6a41_idx",
            old_name="ai_aiprodu_store_i_0fd5e0_idx",
        ),
        migrations.RenameIndex(
            model_name="airequestlog",
            new_name="ai_aireques_store_i_467f69_idx",
            old_name="ai_aireques_store_i_36f4cc_idx",
        ),
        migrations.RenameIndex(
            model_name="airequestlog",
            new_name="ai_aireques_feature_f07395_idx",
            old_name="ai_aireques_feature_2c5f21_idx",
        ),
    ]
