# Generated by ChatGPT on 2026-02-13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0002_aiproductembedding_attributes"),
        ("ai", "0002_rename_ai_aiprodu_store_i_0fd5e0_idx_ai_aiproduc_store_i_ca6a41_idx_and_more"),
    ]

    operations = []
