# Generated by ChatGPT on 2026-02-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0003_merge_0002_migrations"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiproductembedding",
            name="image_fingerprint",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
    ]
