# Generated by Django 5.1.15 on 2026-02-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cart",
            new_name="cart_cart_store_i_de1071_idx",
            old_name="cart_cart_store_i_9c64b3_idx",
        ),
        migrations.RenameIndex(
            model_name="cartitem",
            new_name="cart_cartit_cart_id_6306fd_idx",
            old_name="cart_cartit_cart_id_0b2f4b_idx",
        ),
    ]
