# Generated by Django 5.2.11 on 2026-03-01 07:16

import apps.themes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name_key', models.CharField(max_length=100)),
                ('preview_image_path', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField(db_index=True)),
                ('theme_code', models.CharField(blank=True, default='', max_length=50)),
                ('logo_path', models.ImageField(blank=True, null=True, upload_to=apps.themes.models.branding_logo_upload_to)),
                ('primary_color', models.CharField(blank=True, default='', max_length=7)),
                ('secondary_color', models.CharField(blank=True, default='', max_length=7)),
                ('accent_color', models.CharField(blank=True, default='', max_length=7)),
                ('font_family', models.CharField(blank=True, default='', max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['store_id'], name='themes_stor_store_i_7e1b5a_idx')],
                'constraints': [models.UniqueConstraint(fields=('store_id',), name='uq_store_branding_store')],
            },
        ),
    ]
