# Generated by Codex on 2026-02-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_product_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="weight_kg",
            field=models.DecimalField(decimal_places=3, default=1, max_digits=8),
        ),
    ]

