# Generated by Django 5.1.15 on 2026-02-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("domain", models.CharField(blank=True, default="", max_length=255)),
                ("subdomain", models.CharField(blank=True, default="", max_length=100)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("language", models.CharField(default="ar", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="tenants_ten_is_acti_8f654a_idx"
                    )
                ],
            },
        ),
    ]
