# Generated by Django 5.1.15 on 2026-02-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_tenant_logo_tenant_primary_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantauditlog",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
