# Generated by Django 5.1.15 on 2026-02-06 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_storeprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StorePaymentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("manual", "Manual (offline/COD)"),
                            ("dummy", "Dummy (testing)"),
                            ("gateway", "Gateway (Phase 2)"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "provider_name",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "merchant_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "webhook_secret",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StoreShippingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fulfillment_mode",
                    models.CharField(
                        choices=[
                            ("pickup", "Pickup"),
                            ("manual_delivery", "Manual delivery"),
                            ("carrier", "Carrier (Phase 2)"),
                        ],
                        default="pickup",
                        max_length=20,
                    ),
                ),
                (
                    "origin_city",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "delivery_fee_flat",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="storeprofile",
            name="is_setup_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="storeprofile",
            name="setup_step",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name="storeprofile",
            index=models.Index(
                fields=["setup_step"], name="tenants_sto_setup_s_b0b1e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storeprofile",
            index=models.Index(
                fields=["is_setup_complete"], name="tenants_sto_is_setu_54a21b_idx"
            ),
        ),
        migrations.AddField(
            model_name="storepaymentsettings",
            name="tenant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_settings",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="storeshippingsettings",
            name="tenant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_settings",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="storepaymentsettings",
            index=models.Index(
                fields=["mode", "is_enabled"], name="tenants_sto_mode_0295ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storeshippingsettings",
            index=models.Index(
                fields=["fulfillment_mode", "is_enabled"],
                name="tenants_sto_fulfill_0605c9_idx",
            ),
        ),
    ]
