# Generated by Django 5.1.15 on 2026-02-06

from django.db import migrations


def backfill_storeprofile_setup_step(apps, schema_editor):
    StoreProfile = apps.get_model("tenants", "StoreProfile")
    StoreProfile.objects.filter(store_info_completed=True, setup_step=1).update(setup_step=2)


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0007_storepaymentsettings_storeshippingsettings_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_storeprofile_setup_step, migrations.RunPython.noop),
    ]

