# Generated by Django 5.1.15 on 2026-02-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0008_backfill_storeprofile_setup_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenant",
            name="activated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="deactivated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(
                fields=["is_published"],
                name="tenants_tenant_is_pub_idx",
            ),
        ),
    ]
