# Generated by Django 5.1.15 on 2026-02-19 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_merge_20260217_1400"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="refundrecord",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="refundrecord",
            name="refund_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="refundrecord",
            name="refund_requested_by_idx",
        ),
        migrations.RenameIndex(
            model_name="refundrecord",
            new_name="payments_re_payment_8718b9_idx",
            old_name="refund_payment_status_idx",
        ),
        migrations.RenameIndex(
            model_name="refundrecord",
            new_name="payments_re_created_d71574_idx",
            old_name="refund_created_idx",
        ),
        migrations.AddField(
            model_name="refundrecord",
            name="currency",
            field=models.CharField(default="SAR", max_length=10),
        ),
        migrations.AddField(
            model_name="refundrecord",
            name="reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="paymentprovidersettings",
            name="is_sandbox_mode",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="paymentprovidersettings",
            name="transaction_fee_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Transaction fee percentage (e.g., 2.50 for 2.5%)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="paymentprovidersettings",
            name="wasla_commission_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=3,
                help_text="Wasla platform commission percentage",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="refundrecord",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="refundrecord",
            name="payment_intent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refunds",
                to="payments.paymentintent",
            ),
        ),
        migrations.AlterField(
            model_name="refundrecord",
            name="provider_reference",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="refundrecord",
            name="requested_by",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="refundrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="refundrecord",
            table=None,
        ),
    ]
