# Generated by Django 5.2.11 on 2026-02-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_alter_refundrecord_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="tenant_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="tenant_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="refundrecord",
            name="tenant_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
