# Generated by Django 5.2.11 on 2026-02-20 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_tenant_id_orderitem_tenant_id'),
        ('payments', '0007_payment_tenant_id_paymentintent_tenant_id_and_more'),
        ('stores', '0003_store_tenant_relation'),
        ('tenants', '0011_store_domain_status_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('tap', 'Tap'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=20)),
                ('method', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='created', max_length=20)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=120)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='paymentprovidersettings',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentprovidersettings',
            name='mode',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('prod', 'Production')], default='sandbox', max_length=10),
        ),
        migrations.AddField(
            model_name='paymentprovidersettings',
            name='provider',
            field=models.CharField(blank=True, choices=[('tap', 'Tap'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentprovidersettings',
            name='public_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentprovidersettings',
            name='secret_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentprovidersettings',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_provider_settings', to='stores.store'),
        ),
        migrations.AddIndex(
            model_name='paymentprovidersettings',
            index=models.Index(fields=['store', 'provider', 'is_active'], name='payments_pa_store_i_e28beb_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentprovidersettings',
            constraint=models.UniqueConstraint(fields=('store', 'provider'), name='uq_payment_provider_store_code'),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='orders.order'),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='stores.store'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['store', 'provider', 'status'], name='payments_pa_store_i_39e918_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['provider', 'provider_reference'], name='payments_pa_provide_dfbc5d_idx'),
        ),
    ]
