# Generated by Django 5.2.11 on 2026-02-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_paymentattempt_paymentprovidersettings_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('event_id', models.CharField(max_length=120)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('ignored', 'Ignored'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'event_id'], name='payments_we_provide_139ee0_idx'), models.Index(fields=['status', 'received_at'], name='payments_we_status_4e31df_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='uq_payment_webhook_provider_event')],
            },
        ),
    ]
