# Generated by production hardening upgrade 2026-02-25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0009_webhookevent"),
    ]

    operations = [
        # Add fraud detection fields to PaymentIntent
        migrations.AddField(
            model_name="paymentintent",
            name="risk_score",
            field=models.IntegerField(default=0, help_text="Risk score 0-100, higher is riskier"),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="is_flagged",
            field=models.BooleanField(default=False, db_index=True, help_text="Flagged for manual review"),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="fraud_checks",
            field=models.JSONField(default=dict, blank=True, help_text="Fraud check results"),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="attempt_count",
            field=models.IntegerField(default=0, help_text="Number of payment attempts"),
        ),
        # Add webhook security fields
        migrations.AddField(
            model_name="webhookevent",
            name="signature",
            field=models.CharField(max_length=255, blank=True, default=""),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="signature_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="webhook_timestamp",
            field=models.DateTimeField(null=True, blank=True, help_text="Provider timestamp from webhook"),
        ),
        # Add PaymentAttempt fraud fields
        migrations.AddField(
            model_name="paymentattempt",
            name="risk_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="paymentattempt",
            name="is_flagged",
            field=models.BooleanField(default=False, db_index=True),
        ),
        # Add provider communication log model
        migrations.CreateModel(
            name="ProviderCommunicationLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("provider_code", models.CharField(max_length=50)),
                ("operation", models.CharField(max_length=100, help_text="initiate_payment, verify_callback, refund")),
                ("request_data", models.JSONField(blank=True, default=dict)),
                ("response_data", models.JSONField(blank=True, default=dict)),
                ("status_code", models.IntegerField(null=True, blank=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("duration_ms", models.IntegerField(null=True, blank=True, help_text="Request duration in ms")),
                ("attempt_number", models.IntegerField(default=1)),
                ("idempotency_key", models.CharField(max_length=120, db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["provider_code", "operation", "created_at"], name="payments_pr_provide_7a8f2c_idx"),
                    models.Index(fields=["tenant_id", "created_at"], name="payments_pr_tenant__4b9e1a_idx"),
                    models.Index(fields=["idempotency_key"], name="payments_pr_idempot_8c4d2f_idx"),
                ],
            },
        ),
    ]
