# Generated by Django 5.2.11 on 2026-02-25 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_payment_hardening'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='providercommunicationlog',
            new_name='payments_pr_provide_200664_idx',
            old_name='payments_pr_provide_7a8f2c_idx',
        ),
        migrations.RenameIndex(
            model_name='providercommunicationlog',
            new_name='payments_pr_tenant__9f9ba3_idx',
            old_name='payments_pr_tenant__4b9e1a_idx',
        ),
        migrations.RenameIndex(
            model_name='providercommunicationlog',
            new_name='payments_pr_idempot_55594b_idx',
            old_name='payments_pr_idempot_8c4d2f_idx',
        ),
    ]
