# Generated by Django 5.1.15 on 2026-02-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("themes", "0002_seed_themes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="storebranding",
            new_name="themes_stor_store_i_7e1b5a_idx",
            old_name="themes_stor_store_i_7e4c93_idx",
        ),
    ]
