# Generated by Django 5.1.15 on 2026-02-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0002_webhookevent_payload_raw"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="webhookevent",
            new_name="webhooks_we_provide_dc04c4_idx",
            old_name="webhooks_web_provid_0a8e96_idx",
        ),
        migrations.RenameIndex(
            model_name="webhookevent",
            new_name="webhooks_we_process_22b90b_idx",
            old_name="webhooks_web_process_90b774_idx",
        ),
    ]
