# Generated by Django 5.2.11 on 2026-03-01 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField(db_index=True)),
                ('session_key', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('applied_coupon_code', models.CharField(blank=True, default='', max_length=50)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abandoned_at', models.DateTimeField(blank=True, help_text='When cart was marked as abandoned (24h+ without activity)', null=True)),
                ('reminder_sent', models.BooleanField(default=False, help_text='Whether reminder email has been sent')),
                ('reminder_sent_at', models.DateTimeField(blank=True, help_text='When reminder email was sent', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant')),
            ],
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['store_id', 'updated_at'], name='cart_cart_store_i_de1071_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['abandoned_at'], name='cart_cart_abandon_784b9a_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['reminder_sent'], name='cart_cart_reminde_3ca3bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('store_id', 'user'), name='uq_cart_store_user'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('store_id', 'session_key'), name='uq_cart_store_session'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'created_at'], name='cart_cartit_cart_id_6306fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'variant'), name='uq_cart_item_cart_product_variant'),
        ),
    ]
