# Generated by Django 5.2.11 on 2026-03-01 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField(db_index=True)),
                ('status', models.CharField(choices=[('ADDRESS', 'Address'), ('SHIPPING', 'Shipping'), ('PAYMENT', 'Payment'), ('CONFIRMED', 'Confirmed')], default='ADDRESS', max_length=20)),
                ('shipping_address_json', models.JSONField(blank=True, default=dict)),
                ('shipping_method_code', models.CharField(blank=True, default='', max_length=64)),
                ('totals_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to='cart.cart')),
            ],
        ),
    ]
