# Generated by Django 5.2.11 on 2026-03-01 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_sessions', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='checkoutsession',
            index=models.Index(fields=['store_id', 'status'], name='checkout_ch_store_i_4ddaa2_idx'),
        ),
        migrations.AddIndex(
            model_name='checkoutsession',
            index=models.Index(fields=['store_id', 'created_at'], name='checkout_ch_store_i_665621_idx'),
        ),
    ]
