# Generated by Django 5.1.15 on 2026-02-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="store_id",
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="product",
            name="store_id",
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="catalog.category"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("store_id", "sku"), name="uq_product_store_sku"
            ),
        ),
    ]
