# Generated by Django 5.2.11 on 2026-03-01 10:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('store_id', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'store_id'], name='wallet_wall_tenant__aed203_idx')],
                'constraints': [models.UniqueConstraint(fields=('store_id',), name='uq_wallet_store')],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('balance_bucket', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending')], default='available', max_length=20)),
                ('event_type', models.CharField(choices=[('order_paid', 'Order Paid'), ('order_delivered', 'Order Delivered'), ('refund', 'Refund'), ('withdrawal', 'Withdrawal'), ('adjustment', 'Adjustment')], default='adjustment', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(max_length=255)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'created_at'], name='wallet_wall_tenant__06ea66_idx'), models.Index(fields=['wallet', 'created_at'], name='wallet_wall_wallet__83a8d3_idx'), models.Index(fields=['wallet', 'event_type'], name='wallet_wall_wallet__b881d6_idx'), models.Index(fields=['reference'], name='wallet_wall_referen_b8b9fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('store_id', models.IntegerField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('reference_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('processed_by_user_id', models.IntegerField(blank=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to='wallet.wallet')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='wallet_with_tenant__c7ab74_idx'), models.Index(fields=['store_id', 'requested_at'], name='wallet_with_store_i_a78299_idx')],
            },
        ),
    ]
