# Generated by Django 5.2.11 on 2026-03-01 10:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='SA', max_length=10)),
                ('language', models.CharField(default='ar', max_length=10)),
                ('device_type', models.CharField(default='web', max_length=32)),
                ('business_type', models.CharField(max_length=64)),
                ('expected_products', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_orders_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_profiles', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_plan_code', models.CharField(default='BASIC', max_length=32)),
                ('needs_variants', models.BooleanField(default=False)),
                ('recommended_theme', models.CharField(default='default', max_length=100)),
                ('recommended_categories', models.JSONField(blank=True, default=list)),
                ('shipping_profile', models.JSONField(blank=True, default=dict)),
                ('complexity_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rationale', models.TextField(blank=True, default='')),
                ('llm_used', models.BooleanField(default=False)),
                ('llm_confidence', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_decisions', to='subscriptions.subscriptionplan')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='ai_onboarding.onboardingprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProvisioningActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(default='', max_length=120)),
                ('action', models.CharField(max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioning_action_logs', to='ai_onboarding.onboardingprofile')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_action_logs', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='ProvisioningRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=120)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_requests', to='ai_onboarding.onboardingprofile')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioning_requests', to='stores.store')),
            ],
        ),
        migrations.AddIndex(
            model_name='onboardingprofile',
            index=models.Index(fields=['user', 'created_at'], name='ai_onboardi_user_id_a1df14_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingprofile',
            index=models.Index(fields=['business_type', 'country'], name='ai_onboardi_busines_2cdff9_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingdecision',
            index=models.Index(fields=['recommended_plan_code', 'complexity_score'], name='ai_onboardi_recomme_e008d8_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingdecision',
            index=models.Index(fields=['created_at'], name='ai_onboardi_created_30d8c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='onboardingdecision',
            constraint=models.UniqueConstraint(fields=('profile',), name='uq_onboarding_decision_profile'),
        ),
        migrations.AddIndex(
            model_name='provisioningactionlog',
            index=models.Index(fields=['store', 'created_at'], name='ai_onboardi_store_i_30def9_idx'),
        ),
        migrations.AddIndex(
            model_name='provisioningactionlog',
            index=models.Index(fields=['action', 'status'], name='ai_onboardi_action_10e7fc_idx'),
        ),
        migrations.AddIndex(
            model_name='provisioningactionlog',
            index=models.Index(fields=['idempotency_key'], name='ai_onboardi_idempot_00f613_idx'),
        ),
        migrations.AddIndex(
            model_name='provisioningrequest',
            index=models.Index(fields=['idempotency_key'], name='ai_onboardi_idempot_2576ff_idx'),
        ),
        migrations.AddIndex(
            model_name='provisioningrequest',
            index=models.Index(fields=['status', 'created_at'], name='ai_onboardi_status_ec1990_idx'),
        ),
        migrations.AddConstraint(
            model_name='provisioningrequest',
            constraint=models.UniqueConstraint(fields=('profile', 'idempotency_key'), name='uq_provisioning_profile_idempotency_key'),
        ),
    ]
