# Generated by Django 5.1.15 on 2026-02-07 00:00

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailOtp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("purpose", models.CharField(choices=[("login", "Login"), ("register", "Register"), ("reset", "Reset"), ("generic", "Generic")], default="generic", max_length=32)),
                ("code_hash", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["email", "purpose", "created_at"], name="notificatio_email_a5da4b_idx"),
                    models.Index(fields=["expires_at"], name="notificatio_expires_6f1bb9_idx"),
                ],
            },
        ),
    ]
