# Generated by Django 5.2.11 on 2026-03-01 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('payments', '0001_initial'),
        ('stores', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('store_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['store_id', 'created_at'], name='settlements_store_i_a201b0_idx'), models.Index(fields=['action'], name='settlements_action_d4ca2c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('total_operations', models.PositiveIntegerField(default=0)),
                ('total_wasla_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('store_id', models.IntegerField(db_index=True)),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['store_id', 'currency'], name='settlements_store_i_ab90ae_idx')],
                'constraints': [models.UniqueConstraint(fields=('store_id', 'currency'), name='uq_ledger_account_store_currency')],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('expected_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('settled_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discrepancy', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discrepancy_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('unsettled_orders_count', models.PositiveIntegerField(default=0)),
                ('orphaned_items_count', models.PositiveIntegerField(default=0)),
                ('amount_mismatch_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, default='ok', max_length=20)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_reports', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('store_id', models.IntegerField(db_index=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fees_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('paid', 'Paid'), ('failed', 'Failed')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['store_id', 'created_at'], name='settlements_store_i_3c9ad7_idx'), models.Index(fields=['store_id', 'status'], name='settlements_store_i_b3f359_idx')],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('store_id', models.IntegerField(db_index=True)),
                ('entry_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='orders.order')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='settlements.settlement')),
            ],
        ),
        migrations.CreateModel(
            name='SettlementBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('batch_reference', models.CharField(db_index=True, help_text='Unique identifier for this batch (e.g., BATCH-2026-02-25-001)', max_length=255)),
                ('idempotency_key', models.CharField(db_index=True, help_text='UUID to ensure idempotent processing', max_length=255, unique=True)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_fees', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], db_index=True, default='processing', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.TextField(blank=True, default='')),
                ('orders_succeeded', models.PositiveIntegerField(default=0)),
                ('orders_failed', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_batches', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('calculated_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('calculated_net', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('included', 'Included'), ('processed', 'Processed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='included', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='settlements.settlementbatch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_items', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='SettlementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_items', to='orders.order')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='settlements.settlement')),
            ],
        ),
        migrations.CreateModel(
            name='SettlementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('wasla_fee', models.DecimalField(decimal_places=2, default=1, max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('invoiced', 'Invoiced'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_records', to='orders.order')),
                ('payment_attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_record', to='payments.paymentattempt')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_records', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='settlements.invoice')),
                ('settlement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_line', to='settlements.settlementrecord')),
            ],
        ),
        migrations.CreateModel(
            name='SettlementRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('task_name', models.CharField(db_index=True, max_length=255)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('error_trace', models.TextField(blank=True, default='')),
                ('orders_processed', models.PositiveIntegerField(default=0)),
                ('batches_created', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settlement_run_logs', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'year', 'month'], name='settlements_tenant__7d643d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'created_at'], name='settlements_status_f838ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('tenant', 'year', 'month'), name='uq_invoice_tenant_year_month'),
        ),
        migrations.AddIndex(
            model_name='reconciliationreport',
            index=models.Index(fields=['store', 'created_at'], name='settlements_store_i_e0cf7b_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationreport',
            index=models.Index(fields=['status', 'created_at'], name='settlements_status_9ff361_idx'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationreport',
            constraint=models.UniqueConstraint(fields=('store', 'period_start', 'period_end'), name='uq_reconciliation_report_period'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['store_id', 'created_at'], name='settlements_store_i_ea11f9_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['store_id', 'entry_type'], name='settlements_store_i_dddbf0_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(fields=('order',), name='uq_ledger_entry_order'),
        ),
        migrations.AddIndex(
            model_name='settlementbatch',
            index=models.Index(fields=['store', 'status', 'created_at'], name='settlements_store_i_eee0a1_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementbatch',
            index=models.Index(fields=['idempotency_key'], name='settlements_idempot_76510b_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementbatch',
            index=models.Index(fields=['status', 'created_at'], name='settlements_status_ee0698_idx'),
        ),
        migrations.AddConstraint(
            model_name='settlementbatch',
            constraint=models.UniqueConstraint(fields=('store', 'batch_reference'), name='uq_settlement_batch_reference'),
        ),
        migrations.AddIndex(
            model_name='settlementbatchitem',
            index=models.Index(fields=['batch', 'status'], name='settlements_batch_i_6c9fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementbatchitem',
            index=models.Index(fields=['order'], name='settlements_order_i_a01796_idx'),
        ),
        migrations.AddConstraint(
            model_name='settlementbatchitem',
            constraint=models.UniqueConstraint(fields=('batch', 'order'), name='uq_batch_item_unique'),
        ),
        migrations.AddIndex(
            model_name='settlementitem',
            index=models.Index(fields=['settlement', 'order'], name='settlements_settlem_1abc6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='settlementitem',
            constraint=models.UniqueConstraint(fields=('order',), name='uq_settlement_item_order'),
        ),
        migrations.AddIndex(
            model_name='settlementrecord',
            index=models.Index(fields=['store', 'status', 'created_at'], name='settlements_store_i_22165b_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementrecord',
            index=models.Index(fields=['order'], name='settlements_order_i_1a07c6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['invoice', 'created_at'], name='settlements_invoice_a114f8_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementrunlog',
            index=models.Index(fields=['task_name', 'created_at'], name='settlements_task_na_62f231_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementrunlog',
            index=models.Index(fields=['status', 'created_at'], name='settlements_status_3ff4cf_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementrunlog',
            index=models.Index(fields=['store', 'created_at'], name='settlements_store_i_9e47f5_idx'),
        ),
    ]
