# Generated by Django 5.1.15 on 2026-02-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settlements", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="settlements_store_i_a201b0_idx",
            old_name="auditlog_store_created_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="settlements_action_d4ca2c_idx",
            old_name="auditlog_action_idx",
        ),
        migrations.RenameIndex(
            model_name="ledgeraccount",
            new_name="settlements_store_i_ab90ae_idx",
            old_name="ledgeraccount_store_currency_idx",
        ),
        migrations.RenameIndex(
            model_name="ledgerentry",
            new_name="settlements_store_i_ea11f9_idx",
            old_name="ledgerentry_store_created_idx",
        ),
        migrations.RenameIndex(
            model_name="ledgerentry",
            new_name="settlements_store_i_dddbf0_idx",
            old_name="ledgerentry_store_type_idx",
        ),
        migrations.RenameIndex(
            model_name="settlement",
            new_name="settlements_store_i_3c9ad7_idx",
            old_name="settlement_store_created_idx",
        ),
        migrations.RenameIndex(
            model_name="settlement",
            new_name="settlements_store_i_b3f359_idx",
            old_name="settlement_store_status_idx",
        ),
        migrations.RenameIndex(
            model_name="settlementitem",
            new_name="settlements_settlem_1abc6c_idx",
            old_name="settleitem_settlement_order_idx",
        ),
    ]
