# Generated by Django 5.2.11 on 2026-02-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "settlements",
            "0002_rename_auditlog_store_created_idx_settlements_store_i_a201b0_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="tenant_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="ledgeraccount",
            name="tenant_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="tenant_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="settlement",
            name="tenant_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="settlementitem",
            name="tenant_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
