# Generated by Django 5.2.11 on 2026-02-20 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_tenant_id_orderitem_tenant_id'),
        ('payments', '0009_webhookevent'),
        ('settlements', '0003_auditlog_tenant_id_ledgeraccount_tenant_id_and_more'),
        ('stores', '0003_store_tenant_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('wasla_fee', models.DecimalField(decimal_places=2, default=1, max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('invoiced', 'Invoiced'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_records', to='orders.order')),
                ('payment_attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_record', to='payments.paymentattempt')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_records', to='stores.store')),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'status', 'created_at'], name='settlements_store_i_22165b_idx'), models.Index(fields=['order'], name='settlements_order_i_1a07c6_idx')],
            },
        ),
    ]
