# Generated by Django 5.1.15 on 2026-02-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="store_id",
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["store_id", "is_active"], name="customers_c_store_i_c57c57_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("store_id", "email"), name="uq_customer_store_email"
            ),
        ),
    ]
