# Generated by Django 5.1.15 on 2026-02-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price_monthly", models.DecimalField(decimal_places=2, max_digits=8)),
                ("price_yearly", models.DecimalField(decimal_places=2, max_digits=8)),
                ("is_popular", models.BooleanField(default=False)),
                ("is_free", models.BooleanField(default=False)),
            ],
        ),
    ]
