# Generated by Django 5.2.11 on 2026-02-17 11:51

import django.db.models.deletion
import stores.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Store display name', max_length=255)),
                ('slug', models.SlugField(help_text='URL-safe identifier', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Store description')),
                ('logo', models.ImageField(blank=True, help_text='Store logo image', null=True, upload_to=stores.models.store_logo_upload_to)),
                ('category', models.CharField(blank=True, default='', help_text='Primary business category', max_length=128)),
                ('country', models.CharField(default='SA', help_text='Store country code', max_length=2)),
                ('subdomain', models.CharField(help_text='Subdomain for store (e.g., mystore.visualai.sa)', max_length=255, unique=True)),
                ('custom_domain', models.CharField(blank=True, help_text='Custom domain (premium feature)', max_length=255, null=True, unique=True)),
                ('theme_color_primary', models.CharField(default='#000000', help_text='Primary theme color (hex)', max_length=7)),
                ('theme_color_secondary', models.CharField(default='#ffffff', help_text='Secondary theme color (hex)', max_length=7)),
                ('theme_name', models.CharField(default='default', help_text='Theme template name', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='draft', help_text='Current store status', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured in discover')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('launched_at', models.DateTimeField(blank=True, help_text='When store went live', null=True)),
                ('owner', models.ForeignKey(help_text='User who owns/manages this store', on_delete=django.db.models.deletion.PROTECT, related_name='stores', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, help_text='Subscription plan', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.plan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_on_order', models.BooleanField(default=True)),
                ('notify_email', models.EmailField(blank=True, default='', max_length=254)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('auto_publish_products', models.BooleanField(default=True)),
                ('settlement_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('payout_method', models.CharField(blank=True, default='', help_text='Bank transfer, wallet, etc.', max_length=50)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreSetupStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(choices=[('basic', 'Basic Information'), ('products', 'Product Upload'), ('design', 'Design & Theme'), ('domain', 'Domain Setup')], default='basic', max_length=20)),
                ('completed_steps', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setup_step', to='stores.store')),
            ],
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['owner', 'created_at'], name='stores_stor_owner_i_119437_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['status', 'created_at'], name='stores_stor_status_275131_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['slug'], name='stores_stor_slug_e2ab60_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['subdomain'], name='stores_stor_subdoma_05ddd7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('owner', 'slug')},
        ),
    ]
