#!/usr/bin/env bash
set -Eeuo pipefail

# 03_ocr_setup.sh
# OCR setup:
# - Installs Tesseract OCR + Arabic/English languages
# - Installs poppler-utils
# - Persists TESSDATA_PREFIX
# - Validates OCR health and languages (fails if unhealthy)

PROJECT_NAME="${PROJECT_NAME:-wasla}"
ENV_DIR="/etc/${PROJECT_NAME}"
OCR_ENV_FILE="${ENV_DIR}/ocr.env"
PROFILE_D_FILE="/etc/profile.d/${PROJECT_NAME}_ocr.sh"

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

if [[ "$(id -u)" -ne 0 ]]; then
  fail "Must run as root."
fi

export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y --no-install-recommends \
  tesseract-ocr \
  tesseract-ocr-ara \
  tesseract-ocr-eng \
  poppler-utils

if ! command -v tesseract >/dev/null 2>&1; then
  fail "tesseract not found after installation."
fi

TESSDATA_DIR=""
for candidate in \
  "/usr/share/tesseract-ocr/5/tessdata" \
  "/usr/share/tesseract-ocr/4.00/tessdata" \
  "/usr/share/tesseract-ocr/tessdata" \
  "/usr/share/tesseract/tessdata" \
  "/usr/share/tessdata" \
; do
  if [[ -d "${candidate}" ]] && [[ -f "${candidate}/eng.traineddata" ]] && [[ -f "${candidate}/ara.traineddata" ]]; then
    TESSDATA_DIR="${candidate}"
    break
  fi
done

if [[ -z "${TESSDATA_DIR}" ]]; then
  fail "Unable to locate tessdata directory with ara+eng traineddata."
fi

TESSDATA_PREFIX="$(dirname "${TESSDATA_DIR}")"

mkdir -p "${ENV_DIR}"
cat > "${OCR_ENV_FILE}" <<EOF
TESSDATA_PREFIX=${TESSDATA_PREFIX}
EOF
chmod 0644 "${OCR_ENV_FILE}"

cat > "${PROFILE_D_FILE}" <<EOF
#!/usr/bin/env bash
# Auto-generated by ${PROJECT_NAME} deployment (OCR).
export TESSDATA_PREFIX="${TESSDATA_PREFIX}"
EOF
chmod 0644 "${PROFILE_D_FILE}"

langs="$(tesseract --list-langs 2>/dev/null || true)"
echo "${langs}" | grep -qx "ara" || fail "Tesseract Arabic language (ara) is missing."
echo "${langs}" | grep -qx "eng" || fail "Tesseract English language (eng) is missing."

if ! command -v pdftotext >/dev/null 2>&1; then
  fail "poppler-utils (pdftotext) not found after installation."
fi

echo "OK: OCR healthy. TESSDATA_PREFIX=${TESSDATA_PREFIX}"

