# Generated by Django 5.2.11 on 2026-03-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_code', models.CharField(max_length=50)),
                ('event_id', models.CharField(max_length=120)),
                ('idempotency_key', models.CharField(max_length=180, unique=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('payload_raw', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['provider_code', 'event_id'], name='webhooks_we_provide_dc04c4_idx'), models.Index(fields=['processing_status', 'received_at'], name='webhooks_we_process_22b90b_idx')],
            },
        ),
    ]
