# Generated by Django 5.1.15 on 2026-02-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="event",
            new_name="analytics_e_tenant__53cc1a_idx",
            old_name="analytics_ev_tenant_event_time_idx",
        ),
        migrations.RenameIndex(
            model_name="event",
            new_name="analytics_e_tenant__2070d1_idx",
            old_name="analytics_ev_tenant_time_idx",
        ),
        migrations.RenameIndex(
            model_name="experimentassignment",
            new_name="analytics_e_tenant__45d1a6_idx",
            old_name="analytics_assignment_tenant_time_idx",
        ),
        migrations.RenameIndex(
            model_name="recommendationsnapshot",
            new_name="analytics_r_tenant__36cf0e_idx",
            old_name="analytics_rec_tenant_context_time_idx",
        ),
        migrations.RenameIndex(
            model_name="riskassessment",
            new_name="analytics_r_tenant__b116b8_idx",
            old_name="analytics_risk_tenant_time_idx",
        ),
    ]
