# Generated by Django 5.2.11 on 2026-03-02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanFeature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=150)),
                ("is_enabled", models.BooleanField(default=True)),
                ("limit_value", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="plan_features", to="subscriptions.subscriptionplan")),
            ],
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="code",
            field=models.CharField(blank=True, default="", help_text="Stable plan code (e.g., free/basic/pro/enterprise).", max_length=32),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="sort_order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="storesubscription",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="storesubscription",
            name="trial_ends_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="storesubscription",
            name="current_period_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="storesubscription",
            name="grace_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="storesubscription",
            name="canceled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="planfeature",
            constraint=models.UniqueConstraint(fields=("plan", "code"), name="uq_plan_feature_code"),
        ),
        migrations.AddIndex(
            model_name="planfeature",
            index=models.Index(fields=["plan", "code"], name="subscriptions_planfeature_plan_code_idx"),
        ),
    ]
