# Generated by Django 5.2.11 on 2026-03-02

from django.db import migrations


def _match_plan_code(name: str) -> str | None:
    lowered = (name or "").strip().lower()
    if not lowered:
        return None
    if "enterprise" in lowered:
        return "enterprise"
    if "pro" in lowered:
        return "pro"
    if "basic" in lowered:
        return "basic"
    if "free" in lowered:
        return "free"
    return None


def seed_plans_and_backfill_status(apps, schema_editor):
    SubscriptionPlan = apps.get_model("subscriptions", "SubscriptionPlan")
    StoreSubscription = apps.get_model("subscriptions", "StoreSubscription")

    plan_defs = [
        {"code": "free", "name": "Free", "sort_order": 0},
        {"code": "basic", "name": "Basic", "sort_order": 10},
        {"code": "pro", "name": "Pro", "sort_order": 20},
        {"code": "enterprise", "name": "Enterprise", "sort_order": 30},
    ]

    existing_plans = list(SubscriptionPlan.objects.all())
    total_count = len(existing_plans)

    # Fill missing codes on existing plans (name-based heuristic).
    for plan in existing_plans:
        if not getattr(plan, "code", ""):
            matched = _match_plan_code(getattr(plan, "name", ""))
            if matched:
                plan.code = matched
                if getattr(plan, "sort_order", 0) == 0:
                    for definition in plan_defs:
                        if definition["code"] == matched:
                            plan.sort_order = definition["sort_order"]
                            break
                plan.save(update_fields=["code", "sort_order"])

    existing_codes = {
        code for code in SubscriptionPlan.objects.exclude(code="").values_list("code", flat=True)
    }

    # Create missing plans with conservative defaults.
    for definition in plan_defs:
        if definition["code"] in existing_codes:
            continue
        is_active = definition["code"] == "free"
        SubscriptionPlan.objects.create(
            code=definition["code"],
            name=definition["name"],
            price=0,
            billing_cycle="monthly",
            features=[],
            max_products=None,
            max_orders_monthly=None,
            max_staff_users=None,
            is_active=is_active,
            is_public=True,
            sort_order=definition["sort_order"],
        )

    # Backfill legacy statuses to new enum values.
    StoreSubscription.objects.filter(status="expired").update(status="past_due")
    StoreSubscription.objects.filter(status="cancelled").update(status="canceled")


def reverse_backfill_status(apps, schema_editor):
    StoreSubscription = apps.get_model("subscriptions", "StoreSubscription")
    StoreSubscription.objects.filter(status="past_due").update(status="expired")
    StoreSubscription.objects.filter(status="canceled").update(status="cancelled")


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_add_planfeature_and_subscription_status_fields"),
    ]

    operations = [
        migrations.RunPython(seed_plans_and_backfill_status, reverse_backfill_status),
    ]
