# Generated by Django 5.1.15 on 2026-02-06

from datetime import date, timedelta

from django.db import migrations


def seed_default_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model("subscriptions", "SubscriptionPlan")
    StoreSubscription = apps.get_model("subscriptions", "StoreSubscription")
    Tenant = apps.get_model("tenants", "Tenant")

    plans = [
        {
            "name": "Basic",
            "price": 0,
            "billing_cycle": "monthly",
            "features": ["wallet", "reviews"],
            "max_products": 50,
            "max_orders_monthly": 500,
            "max_staff_users": 3,
        },
        {
            "name": "Pro",
            "price": 49,
            "billing_cycle": "monthly",
            "features": ["wallet", "reviews", "plugins"],
            "max_products": 500,
            "max_orders_monthly": 5000,
            "max_staff_users": 20,
        },
        {
            "name": "Enterprise",
            "price": 199,
            "billing_cycle": "monthly",
            "features": ["wallet", "reviews", "plugins"],
            "max_products": None,
            "max_orders_monthly": None,
            "max_staff_users": None,
        },
    ]

    for plan_data in plans:
        plan, created = SubscriptionPlan.objects.get_or_create(
            name=plan_data["name"],
            defaults=plan_data,
        )
        if not created:
            for key, value in plan_data.items():
                setattr(plan, key, value)
            plan.is_active = True
            plan.save()

    default_tenant = Tenant.objects.filter(slug="default").first()
    if not default_tenant:
        return

    basic_plan = SubscriptionPlan.objects.filter(name="Basic", is_active=True).first()
    if not basic_plan:
        return

    today = date.today()
    has_active = StoreSubscription.objects.filter(
        store_id=default_tenant.id,
        status="active",
        end_date__gte=today,
    ).exists()
    if has_active:
        return

    start = today
    end = start + (timedelta(days=30) if basic_plan.billing_cycle == "monthly" else timedelta(days=365))
    StoreSubscription.objects.create(
        store_id=default_tenant.id,
        plan=basic_plan,
        start_date=start,
        end_date=end,
        status="active",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0002_create_default_tenant"),
        ("subscriptions", "0002_subscriptionplan_max_orders_monthly_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_default_plans, migrations.RunPython.noop),
    ]

