# Generated by Codex on 2026-02-23

from django.db import migrations


def apply_default_features(apps, schema_editor):
    SubscriptionPlan = apps.get_model("subscriptions", "SubscriptionPlan")
    defaults = {
        "Basic": [],
        "Plus": ["custom_domain"],
        "Pro": ["custom_domain", "ai_tools", "ai_visual_search"],
        "Business": ["custom_domain", "ai_tools", "ai_visual_search"],
    }

    for name, features in defaults.items():
        plans = SubscriptionPlan.objects.filter(name=name)
        for plan in plans:
            if not plan.features:
                plan.features = features
                plan.save(update_fields=["features"])


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0004_payment_transaction"),
    ]

    operations = [
        migrations.RunPython(apply_default_features, migrations.RunPython.noop),
    ]
