# Generated by Codex on 2026-02-28

from django.db import migrations


def add_payment_methods(apps, schema_editor):
    """Backfill payment method features to existing plans."""
    SubscriptionPlan = apps.get_model("subscriptions", "SubscriptionPlan")
    
    # Map plan names to payment methods they should support
    payment_features_map = {
        "Basic": [],
        "Plus": ["tap", "stripe"],
        "Pro": ["tap", "stripe", "stc_pay"],
        "Business": ["tap", "stripe", "stc_pay"],
    }

    for plan_name, payment_methods in payment_features_map.items():
        plans = SubscriptionPlan.objects.filter(name=plan_name)
        for plan in plans:
            if plan.features is None:
                plan.features = payment_methods
            else:
                # Append payment methods if not already present
                existing_features = set(plan.features or [])
                new_features = list(existing_features.union(set(payment_methods)))
                plan.features = sorted(new_features)
            
            plan.save(update_fields=["features"])


def remove_payment_methods(apps, schema_editor):
    """Reverse: remove payment method features from plans."""
    SubscriptionPlan = apps.get_model("subscriptions", "SubscriptionPlan")
    
    payment_methods = {"tap", "stripe", "stc_pay"}
    
    for plan in SubscriptionPlan.objects.all():
        if plan.features:
            plan.features = [f for f in plan.features if f not in payment_methods]
            plan.save(update_fields=["features"])


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0005_default_plan_features"),
    ]

    operations = [
        migrations.RunPython(add_payment_methods, remove_payment_methods),
    ]
