# Generated by Django 5.2.11 on 2026-03-01 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField(db_index=True)),
                ('feature', models.CharField(choices=[('DESCRIPTION', 'Description'), ('CATEGORY', 'Category'), ('SEARCH', 'Search')], max_length=20)),
                ('provider', models.CharField(default='', max_length=50)),
                ('latency_ms', models.IntegerField(default=0)),
                ('token_count', models.IntegerField(blank=True, null=True)),
                ('cost_estimate', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['store_id', 'created_at'], name='ai_aireques_store_i_467f69_idx'), models.Index(fields=['feature', 'created_at'], name='ai_aireques_feature_f07395_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIProductEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField(db_index=True)),
                ('provider', models.CharField(default='', max_length=50)),
                ('image_fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('vector', models.JSONField(blank=True, default=list)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_embedding', to='catalog.product')),
            ],
            options={
                'indexes': [models.Index(fields=['store_id', 'created_at'], name='ai_aiproduc_store_i_ca6a41_idx')],
            },
        ),
    ]
