# Generated by Django 5.2.11 on 2026-03-01 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentlineitem',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='shipping.shipment'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservation', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.productvariant'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store_id', 'created_at'], name='orders_orde_store_i_8955ea_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store_id', 'status'], name='orders_orde_store_i_610c63_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant_id', 'status'], name='orders_orde_tenant__291115_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant_id', 'status'], name='orders_invo_tenant__701494_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['order'], name='orders_invo_order_i_e9463d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date'], name='orders_invo_issue_d_239a92_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicelineitem',
            index=models.Index(fields=['invoice_id'], name='orders_invo_invoice_bff9e5_idx'),
        ),
        migrations.AddIndex(
            model_name='returnmerchandiseauthorization',
            index=models.Index(fields=['tenant_id', 'status'], name='orders_retu_tenant__8659a2_idx'),
        ),
        migrations.AddIndex(
            model_name='returnmerchandiseauthorization',
            index=models.Index(fields=['order'], name='orders_retu_order_i_5f181a_idx'),
        ),
        migrations.AddIndex(
            model_name='returnitem',
            index=models.Index(fields=['tenant_id'], name='orders_retu_tenant__a3aa0a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='returnitem',
            unique_together={('rma', 'order_item')},
        ),
        migrations.AddIndex(
            model_name='refundtransaction',
            index=models.Index(fields=['tenant_id', 'status'], name='orders_refu_tenant__68e046_idx'),
        ),
        migrations.AddIndex(
            model_name='refundtransaction',
            index=models.Index(fields=['order'], name='orders_refu_order_i_14e7c6_idx'),
        ),
        migrations.AddIndex(
            model_name='refundtransaction',
            index=models.Index(fields=['provider_refund_id'], name='orders_refu_provide_025836_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentlineitem',
            index=models.Index(fields=['tenant_id'], name='orders_ship_tenant__053a62_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shipmentlineitem',
            unique_together={('shipment', 'order_item')},
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['tenant_id', 'status'], name='orders_stoc_tenant__a34742_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['product', 'status'], name='orders_stoc_product_180af8_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['expires_at'], name='orders_stoc_expires_f55a9e_idx'),
        ),
    ]
