# Generated by Django 5.2.11 on 2026-02-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_checkout_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tenant_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="tenant_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
