# Generated by Django 5.2.11 on 2026-02-28 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_variant'),
        ('orders', '0003_order_checkout_fields'),
    ]

    operations = [
    ]
