# Generated by Codex on 2026-02-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_production_commerce"),
        ("catalog", "0009_product_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon_code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="confirmation_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stockreservation",
            name="store_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="stockreservation",
            name="release_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="returnmerchandiseauthorization",
            name="store_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.RenameField(
            model_name="returnmerchandiseauthorization",
            old_name="reason_notes",
            new_name="reason_description",
        ),
        migrations.AddField(
            model_name="returnmerchandiseauthorization",
            name="is_exchange",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="returnmerchandiseauthorization",
            name="exchange_product",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="catalog.product"),
        ),
        migrations.AddField(
            model_name="returnmerchandiseauthorization",
            name="return_tracking_number",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="returnmerchandiseauthorization",
            name="return_carrier",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="returnmerchandiseauthorization",
            name="requested_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="returnmerchandiseauthorization",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="returnmerchandiseauthorization",
            name="received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="returnmerchandiseauthorization",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="returnitem",
            name="refund_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="returnitem",
            name="status",
            field=models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected"), ("refunded", "Refunded")], default="pending", max_length=20),
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="shipping_charge",
            new_name="shipping_cost",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="seller_vat_number",
            new_name="seller_vat_id",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="buyer_vat_number",
            new_name="buyer_vat_id",
        ),
        migrations.AddField(
            model_name="invoice",
            name="store_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax_rate",
            field=models.DecimalField(decimal_places=2, default="15", max_digits=5),
        ),
        migrations.AddField(
            model_name="invoice",
            name="buyer_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="invoice",
            name="buyer_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="invoice",
            name="seller_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="invoice",
            name="seller_address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="invoice",
            name="seller_bank_details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="invoice",
            name="zatca_qr_code",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="invoice",
            name="zatca_uuid",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="invoice",
            name="zatca_hash",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="invoice",
            name="zatca_signed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="currency",
            field=models.CharField(default="SAR", max_length=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("description", models.CharField(max_length=255)),
                ("sku", models.CharField(blank=True, max_length=100)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("line_subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                ("line_tax", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="line_items", to="orders.invoice")),
                ("order_item", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="orders.orderitem")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["invoice_id"], name="orders_invoice_line_item_invoice_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="refundtransaction",
            name="refund_id",
            field=models.CharField(blank=True, default="", max_length=64, unique=True),
        ),
        migrations.RenameField(
            model_name="refundtransaction",
            old_name="reason",
            new_name="refund_reason",
        ),
        migrations.AddField(
            model_name="refundtransaction",
            name="store_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
