# Generated by Django 5.1.15 on 2026-02-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalEmailSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("smtp", "SMTP"),
                            ("sendgrid", "SendGrid"),
                            ("mailgun", "Mailgun"),
                            ("ses", "AWS SES"),
                        ],
                        default="smtp",
                        max_length=20,
                    ),
                ),
                ("host", models.CharField(blank=True, default="", max_length=255)),
                ("port", models.PositiveIntegerField(default=587)),
                ("username", models.CharField(blank=True, default="", max_length=255)),
                ("password_encrypted", models.TextField(blank=True, default="")),
                (
                    "from_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("use_tls", models.BooleanField(default=True)),
                ("enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["provider", "enabled"],
                        name="emails_glob_provide_ce90a4_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GlobalEmailSettingsAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=64)),
                (
                    "actor",
                    models.CharField(blank=True, default="system", max_length=150),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"],
                        name="emails_glob_action_42aadd_idx",
                    )
                ],
            },
        ),
    ]
