# Generated by Django 5.1.15 on 2026-02-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="checkoutsession",
            new_name="checkout_ch_store_i_4ddaa2_idx",
            old_name="checkout_che_store_i_79fd32_idx",
        ),
        migrations.RenameIndex(
            model_name="checkoutsession",
            new_name="checkout_ch_store_i_665621_idx",
            old_name="checkout_che_store_i_67ed5c_idx",
        ),
    ]
