# Generated by Django 5.1.15 on 2026-02-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_customer_store_id_alter_customer_email_and_more"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="store_id",
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["store_id", "created_at"], name="orders_orde_store_i_8955ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["store_id", "status"], name="orders_orde_store_i_610c63_idx"
            ),
        ),
    ]
